import { beachPalette } from '../../assets/palette';
import type { BiomeDefinition } from '../../engine/types';
import {
  beachGrassEntry,
  beachPeaEntry,
  beachStrawberryEntry,
  duneLupineEntry,
  sandVerbenaEntry,
  seaRocketEntry,
} from '../shared-entries';

const beachEntries = {
  'native-littleneck-shell': {
    id: 'native-littleneck-shell',
    commonName: 'Pacific Littleneck Shell',
    scientificName: 'Leukoma staminea',
    category: 'shell',
    shortFact: 'Pacific littlenecks stay buried a few inches deep in sand or gravel.',
    journalText:
      'Pacific littlenecks are clams with rounded shells marked by rings and lines. They spend much of their lives buried below the surface on Pacific shorelines.',
    spriteId: 'native-littleneck-shell',
    collectible: true,
  },
  'moon-snail-shell': {
    id: 'moon-snail-shell',
    commonName: "Lewis' Moon Snail Shell",
    scientificName: 'Neverita lewisii',
    category: 'shell',
    shortFact: 'Lewis moon snails live in sandy places and have one large rounded whorl.',
    journalText:
      "Lewis' moon snails live on Pacific coasts in sandy places protected from heavy surf. Their big rounded shells belong to one of the largest snails along this coast.",
    sketchbookNote: 'Round shell clue from calmer sand.',
    spriteId: 'moon-snail-shell',
    collectible: true,
  },
  'razor-clam-shell': {
    id: 'razor-clam-shell',
    commonName: 'Pacific Razor Clam Shell',
    scientificName: 'Siliqua patula',
    category: 'shell',
    shortFact: 'Razor clams have long narrow shells and live on Pacific ocean beaches.',
    journalText:
      'Pacific razor clams live on ocean beaches from California to Alaska. Their long shells help them fit into wet sand where waves rise and fall.',
    spriteId: 'razor-clam-shell',
    collectible: true,
  },
  'sand-dollar-test': {
    id: 'sand-dollar-test',
    commonName: 'Pacific Sand Dollar Test',
    scientificName: 'Dendraster excentricus',
    category: 'animal',
    shortFact: 'A sand dollar test is the hard body left after the living animal loses its tiny spines.',
    journalText:
      'Pacific sand dollars are sea urchin relatives that burrow partway into sandy shore bottoms. After one dies and dries, its pale hard test can wash onto the beach.',
    sketchbookNote: 'A pale shore clue washed from sandy shallows.',
    spriteId: 'sand-dollar-test',
    collectible: true,
  },
  'beach-grass': beachGrassEntry,
  'beach-pea': beachPeaEntry,
  'dune-lupine': duneLupineEntry,
  'beach-strawberry': beachStrawberryEntry,
  'sand-verbena': sandVerbenaEntry,
  'sea-rocket': seaRocketEntry,
  'western-snowy-plover': {
    id: 'western-snowy-plover',
    commonName: 'Western Snowy Plover',
    scientificName: 'Charadrius nivosus nivosus',
    category: 'animal',
    shortFact: 'Western snowy plovers nest right on open sand where beaches stay wide and quiet.',
    journalText:
      'Western snowy plovers are small shorebirds that rest and nest on open sandy beaches. They depend on wide beach habitat where nests are easier to spot and protect.',
    sketchbookNote: 'Small shore bird reading the open wrack line.',
    spriteId: 'western-snowy-plover',
    collectible: false,
  },
  'pacific-sand-crab': {
    id: 'pacific-sand-crab',
    commonName: 'Pacific Sand Crab',
    scientificName: 'Emerita analoga',
    category: 'animal',
    shortFact: 'Pacific sand crabs are important food for fishes and shorebirds.',
    journalText:
      'Pacific sand crabs live in the surf zone of sandy beaches. Healthy wet sand and kelp wrack help support them and the birds that feed on them.',
    sketchbookNote: 'Quick burrower working the wet wrack edge.',
    spriteId: 'pacific-sand-crab',
    collectible: false,
  },
  'beach-hopper': {
    id: 'beach-hopper',
    commonName: 'Beach Hopper',
    scientificName: 'Megalorchestia spp.',
    category: 'animal',
    shortFact: 'Beach hoppers hide in wrack and help break washed-up seaweed into smaller pieces.',
    journalText:
      'Beach hoppers are small shore crustaceans that tuck into wrack and damp sand. They help turn washed-up kelp into food for other beach animals.',
    sketchbookNote: 'Tiny wrack scavenger hopping under kelp.',
    spriteId: 'beach-hopper',
    collectible: false,
  },
  sanderling: {
    id: 'sanderling',
    commonName: 'Sanderling',
    scientificName: 'Calidris alba',
    category: 'animal',
    shortFact: 'Sanderlings chase waves to find tiny animals in wet sand.',
    journalText:
      'Sanderlings are small shorebirds that race along the waterline. Their quick legs help them follow the retreating surf to hunt for food.',
    sketchbookNote: 'Quick feet tracing retreating surf.',
    spriteId: 'sanderling',
    collectible: false,
  },
  'driftwood-log': {
    id: 'driftwood-log',
    commonName: 'Driftwood',
    category: 'landmark',
    subtitle: 'Shelter and shade',
    subtitleLabel: 'Habitat role',
    shortFact: 'Driftwood can create shelter for tiny beach animals and insects.',
    journalText:
      'Driftwood is wood that has been carried by water and waves. It becomes part of the shoreline habitat and can offer shade and shelter.',
    sketchbookNote: 'Bleached wood making shade above the sand.',
    spriteId: 'driftwood-log',
    collectible: false,
  },
  'bull-kelp-wrack': {
    id: 'bull-kelp-wrack',
    commonName: 'Bull Kelp Wrack',
    category: 'landmark',
    subtitle: 'Washed-up food raft',
    subtitleLabel: 'Habitat role',
    shortFact: 'Washed-up kelp can feed tiny beach insects and the birds that eat them.',
    journalText:
      'Bull kelp can wash ashore after storms and tides. On the beach, wrack becomes food and shelter for small animals that help feed shorebirds.',
    sketchbookNote: 'Kelp ribbons left as beach food and cover.',
    spriteId: 'bull-kelp-wrack',
    collectible: false,
  },
} satisfies BiomeDefinition['entries'];

export const beachBiome: BiomeDefinition = {
  id: 'beach',
  name: 'Sunny Beach',
  palette: beachPalette,
  tileSet: ['sand-top', 'sand-fill', 'rock-platform'],
  parallaxLayers: [
    { id: 'far-dunes', speed: 0.2, color: '#f2d7a6', amplitude: 6, baseY: 84 },
    { id: 'sea-band', speed: 0.45, color: '#6cb5c6', amplitude: 3, baseY: 96 },
  ],
  terrainRules: {
    worldWidth: 640,
    worldHeight: 144,
    sampleStep: 16,
    zones: [
      { id: 'dune-edge', label: 'Dune Edge', start: 0, end: 146, surfaceBaseY: 104, surfaceVariance: 7 },
      { id: 'dry-sand', label: 'Dry Sand', start: 146, end: 288, surfaceBaseY: 112, surfaceVariance: 4 },
      { id: 'lee-pocket', label: 'Lee Pocket', start: 288, end: 400, surfaceBaseY: 123, surfaceVariance: 2 },
      { id: 'tide-line', label: 'Tide Line', start: 400, end: 514, surfaceBaseY: 118, surfaceVariance: 3 },
      { id: 'tidepool', label: 'Tidepool', start: 514, end: 640, surfaceBaseY: 114, surfaceVariance: 6 },
    ],
    platformRules: [
      {
        id: 'dune-step',
        zoneId: 'dune-edge',
        minCount: 1,
        maxCount: 2,
        minWidth: 18,
        maxWidth: 28,
        height: 4,
        liftMin: 8,
        liftMax: 14,
        spriteId: 'rock-platform',
      },
      {
        id: 'tidepool-ledge',
        zoneId: 'tidepool',
        minCount: 2,
        maxCount: 3,
        minWidth: 14,
        maxWidth: 22,
        height: 4,
        liftMin: 6,
        liftMax: 12,
        spriteId: 'rock-platform',
      },
    ],
    authoredPlatforms: [
      {
        id: 'dune-shoulder-entry-lip',
        spriteId: 'rock-platform',
        x: 126,
        y: 106,
        w: 18,
        h: 4,
      },
      {
        id: 'dune-shoulder-rest',
        spriteId: 'rock-platform',
        x: 152,
        y: 101,
        w: 28,
        h: 4,
      },
      {
        id: 'dune-crest-entry-step',
        spriteId: 'rock-platform',
        x: 222,
        y: 102,
        w: 20,
        h: 4,
      },
      {
        id: 'dune-crest-mid-step',
        spriteId: 'rock-platform',
        x: 250,
        y: 96,
        w: 22,
        h: 4,
      },
      {
        id: 'dune-crest-view',
        spriteId: 'rock-platform',
        x: 280,
        y: 92,
        w: 26,
        h: 4,
      },
      {
        id: 'lee-pocket-entry-drift',
        spriteId: 'drift-platform',
        x: 304,
        y: 109,
        w: 20,
        h: 4,
      },
      {
        id: 'lee-pocket-drift-span',
        spriteId: 'drift-platform',
        x: 330,
        y: 101,
        w: 64,
        h: 4,
      },
      {
        id: 'lee-pocket-exit-drift',
        spriteId: 'drift-platform',
        x: 400,
        y: 109,
        w: 22,
        h: 4,
      },
      {
        id: 'tidepool-approach-drift',
        spriteId: 'drift-platform',
        x: 462,
        y: 110,
        w: 24,
        h: 4,
      },
      {
        id: 'tidepool-approach-sill',
        spriteId: 'drift-platform',
        x: 498,
        y: 104,
        w: 26,
        h: 4,
      },
      {
        id: 'tidepool-overlook',
        spriteId: 'drift-platform',
        x: 534,
        y: 99,
        w: 28,
        h: 4,
      },
    ],
    authoredEntities: [
      {
        id: 'dune-shoulder-grass',
        entryId: 'beach-grass',
        x: 132,
        y: 95,
      },
      {
        id: 'dune-shoulder-pea',
        entryId: 'beach-pea',
        x: 160,
        y: 95,
      },
      {
        id: 'dune-shoulder-verbena',
        entryId: 'sand-verbena',
        x: 178,
        y: 96,
      },
      {
        id: 'dry-sand-lupine-clump',
        entryId: 'dune-lupine',
        x: 236,
        y: 98,
      },
      {
        id: 'lee-pocket-lupine-clump',
        entryId: 'dune-lupine',
        x: 304,
        y: 109,
      },
      {
        id: 'lee-pocket-strawberry-patch',
        entryId: 'beach-strawberry',
        x: 350,
        y: 111,
      },
      {
        id: 'lee-pocket-hopper',
        entryId: 'beach-hopper',
        x: 366,
        y: 117,
      },
      {
        id: 'dune-crest-verbena-clump',
        entryId: 'sand-verbena',
        x: 284,
        y: 97,
      },
      {
        id: 'tidepool-approach-wrack',
        entryId: 'bull-kelp-wrack',
        x: 486,
        y: 113,
      },
      {
        id: 'tidepool-approach-crab',
        entryId: 'pacific-sand-crab',
        x: 516,
        y: 112,
      },
      {
        id: 'tidepool-overlook-clue',
        entryId: 'sand-dollar-test',
        x: 548,
        y: 104,
      },
    ],
  },
  spawnTables: [
    {
      id: 'stable-plants',
      zoneId: 'dune-edge',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 26,
      entries: [
        { entryId: 'beach-grass', weight: 5 },
        { entryId: 'beach-pea', weight: 1 },
        { entryId: 'sand-verbena', weight: 2 },
        { entryId: 'sea-rocket', weight: 1 },
      ],
    },
    {
      id: 'stable-shore-plants',
      zoneId: 'dry-sand',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 34,
      entries: [
        { entryId: 'sand-verbena', weight: 4 },
        { entryId: 'beach-pea', weight: 3 },
        { entryId: 'beach-grass', weight: 2 },
        { entryId: 'sea-rocket', weight: 1 },
      ],
    },
    {
      id: 'stable-dry-sand-runners',
      zoneId: 'dry-sand',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 30,
      entries: [{ entryId: 'beach-pea', weight: 1 }],
    },
    {
      id: 'stable-dry-sand-lupine',
      zoneId: 'dry-sand',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 34,
      entries: [{ entryId: 'dune-lupine', weight: 1 }],
    },
    {
      id: 'stable-landmark',
      zoneId: 'lee-pocket',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 12,
      entries: [{ entryId: 'driftwood-log', weight: 1 }],
    },
    {
      id: 'stable-lee-pocket-runners',
      zoneId: 'lee-pocket',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 26,
      entries: [{ entryId: 'beach-strawberry', weight: 1 }],
    },
    {
      id: 'wrack-line',
      zoneId: 'tide-line',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 36,
      entries: [
        { entryId: 'bull-kelp-wrack', weight: 2 },
        { entryId: 'beach-hopper', weight: 2 },
      ],
    },
    {
      id: 'shells',
      zoneId: 'tide-line',
      refreshPolicy: 'visit',
      minCount: 4,
      maxCount: 6,
      spacing: 16,
      entries: [
        { entryId: 'native-littleneck-shell', weight: 5 },
        { entryId: 'moon-snail-shell', weight: 3 },
        { entryId: 'razor-clam-shell', weight: 2 },
        { entryId: 'sand-dollar-test', weight: 2 },
      ],
    },
    {
      id: 'tidepool-shells',
      zoneId: 'tidepool',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 18,
      entries: [
        { entryId: 'moon-snail-shell', weight: 3 },
        { entryId: 'razor-clam-shell', weight: 2 },
        { entryId: 'sand-dollar-test', weight: 1 },
      ],
    },
    {
      id: 'shore-animals',
      zoneId: 'tide-line',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 4,
      spacing: 28,
      entries: [
        { entryId: 'pacific-sand-crab', weight: 3 },
        { entryId: 'sanderling', weight: 2 },
        { entryId: 'western-snowy-plover', weight: 2 },
      ],
    },
    {
      id: 'lee-pocket-life',
      zoneId: 'lee-pocket',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 24,
      entries: [
        { entryId: 'bull-kelp-wrack', weight: 2 },
        { entryId: 'beach-hopper', weight: 3 },
        { entryId: 'pacific-sand-crab', weight: 2 },
        { entryId: 'sanderling', weight: 1 },
      ],
    },
  ],
  ambientRules: {
    cloudCount: [2, 4],
    sparkleCount: [10, 18],
  },
  entries: beachEntries,
  ecosystemNotes: [
    {
      id: 'low-dune-bloom',
      title: 'Low Dune Bloom',
      entryIds: ['sand-verbena', 'beach-grass'],
      minimumDiscoveries: 2,
      summary:
        'Sand verbena stays low beside dunegrass where the first dunes still take full wind and salt.',
      observationPrompt:
        'Which low flowers still look protected here?',
      zoneId: 'dune-edge',
    },
    {
      id: 'low-runner-band',
      title: 'Low Runner Band',
      entryIds: ['beach-pea', 'dune-lupine', 'sand-verbena'],
      minimumDiscoveries: 2,
      summary:
        'Low runners and early blooms show where drier sand starts holding a little more cover.',
      observationPrompt:
        'Where do the first blooms hold by the runners?',
      zoneId: 'dry-sand',
    },
    {
      id: 'lee-pocket-hold',
      title: 'Lee Pocket Hold',
      entryIds: ['driftwood-log', 'dune-lupine', 'beach-strawberry'],
      minimumDiscoveries: 2,
      summary:
        'Driftwood and calmer sand let low runners and blooms keep holding in this tucked pocket.',
      observationPrompt:
        'Which plants look tucked into calmer sand?',
      zoneId: 'lee-pocket',
    },
    {
      id: 'shore-shelter',
      title: 'Shore Shelter',
      entryIds: ['beach-grass', 'driftwood-log', 'pacific-sand-crab'],
      summary:
        'Roots and driftwood make calm hiding spots for small beach animals.',
      observationPrompt:
        'Where looks safer by grass or wood?',
      zoneId: 'dune-edge',
    },
    {
      id: 'shelter-line-start',
      title: 'Shelter Line Start',
      entryIds: ['sea-rocket', 'sand-verbena', 'beach-grass'],
      minimumDiscoveries: 2,
      summary:
        'The lowest exposed plants mark where the first shelter line starts on open beach.',
      observationPrompt:
        'Which low plants mark the first shelter line?',
      zoneId: 'dune-edge',
    },
    {
      id: 'washed-clues',
      title: 'Washed Clues',
      entryIds: ['sand-dollar-test', 'moon-snail-shell', 'bull-kelp-wrack'],
      minimumDiscoveries: 2,
      summary:
        'The tide line mixes wrack with empty remains, so waves leave clues from just offshore.',
      observationPrompt:
        'Which clues here were washed in by waves?',
      zoneId: 'tide-line',
    },
    {
      id: 'wave-edge-survivors',
      title: 'Wrack Workers',
      entryIds: ['bull-kelp-wrack', 'beach-hopper', 'pacific-sand-crab'],
      minimumDiscoveries: 2,
      summary:
        'Wrack feeds tiny scavengers and small beach animals before birds rush in.',
      observationPrompt:
        'What in this wrack feeds small animals first?',
      zoneId: 'tide-line',
    },
    {
      id: 'surf-food-line',
      title: 'Surf Food Line',
      entryIds: ['sanderling', 'pacific-sand-crab', 'bull-kelp-wrack'],
      minimumDiscoveries: 2,
      summary:
        'Quick shorebirds follow the moving food line where waves uncover tiny beach animals by wrack.',
      observationPrompt:
        'What looks uncovered just before birds run in?',
      zoneId: 'tide-line',
    },
  ],
  phenology: {
    phases: {
      early: {
        skyWashTop: 'rgba(245, 244, 216, 0.14)',
        skyWashBottom: 'rgba(248, 245, 226, 0.08)',
        groundWash: 'rgba(222, 226, 166, 0.12)',
        parallaxColors: ['#e4d09a', '#6fb1c0'],
        entryAccents: [
          {
            entryId: 'beach-grass',
            style: 'tuft',
            primaryColor: '#7d9d57',
            secondaryColor: '#c3d47d',
            spriteId: 'beach-grass-early',
          },
          {
            entryId: 'sand-verbena',
            style: 'tuft',
            primaryColor: '#91aa59',
            secondaryColor: '#e4d79b',
            spriteId: 'sand-verbena-early',
          },
        ],
      },
      peak: {
        skyWashTop: 'rgba(255, 237, 190, 0.12)',
        skyWashBottom: 'rgba(244, 248, 236, 0.08)',
        groundWash: 'rgba(228, 214, 138, 0.14)',
        parallaxColors: ['#f0cf92', '#72b8c8'],
        entryAccents: [
          {
            entryId: 'beach-grass',
            style: 'tuft',
            primaryColor: '#8aaa57',
            secondaryColor: '#d7df8a',
            spriteId: 'beach-grass-peak',
          },
          {
            entryId: 'sand-verbena',
            style: 'bloom',
            primaryColor: '#f4cf62',
            secondaryColor: '#fff3ce',
            spriteId: 'sand-verbena-peak',
          },
        ],
      },
      late: {
        skyWashTop: 'rgba(238, 214, 176, 0.14)',
        skyWashBottom: 'rgba(236, 225, 198, 0.08)',
        groundWash: 'rgba(205, 182, 118, 0.18)',
        parallaxColors: ['#dcb57e', '#5f9bae'],
        entryAccents: [
          {
            entryId: 'sand-verbena',
            style: 'seed',
            primaryColor: '#cc9e60',
            secondaryColor: '#f1dab3',
            spriteId: 'sand-verbena-late',
          },
          {
            entryId: 'beach-grass',
            style: 'seed',
            primaryColor: '#d0b36a',
            secondaryColor: '#f3e2a6',
            spriteId: 'beach-grass-late',
          },
          { entryId: 'bull-kelp-wrack', style: 'tuft', primaryColor: '#6b7b46', secondaryColor: '#b7aa78' },
        ],
        spawnEmphasis: [{ tableId: 'wrack-line', minCountDelta: 1, maxCountDelta: 1 }],
      },
    },
  },
  processMoments: [
    {
      id: 'wrack-hold',
      style: 'moisture-hold',
      entryIds: ['bull-kelp-wrack', 'beach-hopper', 'pacific-sand-crab'],
      zoneIds: ['tide-line'],
      minimumVisitCount: 2,
      weatherProfiles: ['marine-haze'],
      phenologyPhases: ['late'],
      primaryColor: '#6b7b46',
      secondaryColor: '#d9cf9d',
    },
  ],
  startPosition: {
    x: 28,
    y: 80,
  },
};
