import { coastalScrubPalette } from '../../assets/palette';
import type { BiomeDefinition } from '../../engine/types';
import {
  beachGrassEntry,
  beachPeaEntry,
  nootkaRoseEntry,
  salmonberryEntry,
  sandVerbenaEntry,
  seaRocketEntry,
  swordFernEntry,
} from '../shared-entries';

const coastalScrubEntries = {
  'beach-grass': beachGrassEntry,
  'beach-pea': beachPeaEntry,
  'sand-verbena': sandVerbenaEntry,
  'sea-rocket': seaRocketEntry,
  'dune-lupine': {
    id: 'dune-lupine',
    commonName: 'Seashore Lupine',
    scientificName: 'Lupinus littoralis',
    category: 'plant',
    shortFact: 'Seashore lupine can grow in poor sand where wind and salt make life hard.',
    journalText:
      'Seashore lupine is one of the native flowers that brightens Pacific dunes. Pioneer plants like this help prepare harsh coastal ground for later shrubs.',
    spriteId: 'dune-lupine',
    collectible: false,
  },
  'pacific-wax-myrtle': {
    id: 'pacific-wax-myrtle',
    commonName: 'Pacific Wax Myrtle',
    scientificName: 'Myrica californica',
    category: 'plant',
    shortFact: 'Pacific wax myrtle can grow in poor coastal soil where many shrubs struggle.',
    journalText:
      'Pacific wax myrtle is an evergreen coastal shrub with dark waxy berries. Root nodules help it grow in relatively poor soils as dunes become more sheltered.',
    spriteId: 'pacific-wax-myrtle',
    collectible: false,
  },
  'coyote-brush': {
    id: 'coyote-brush',
    commonName: 'Coyote Brush',
    scientificName: 'Baccharis pilularis',
    category: 'plant',
    shortFact: 'Coyote brush is one of the shrubs that shows Pacific coastal scrub has begun.',
    journalText:
      'Coyote brush is a tough native shrub that can cover windy Pacific coastal scrub. Dense branches help mark the shift from open dune plants to brushier habitat.',
    spriteId: 'coyote-brush',
    collectible: false,
  },
  'shore-pine': {
    id: 'shore-pine',
    commonName: 'Shore Pine',
    scientificName: 'Pinus contorta var. contorta',
    category: 'plant',
    shortFact: 'Shore pine can grow in windy places with sandy, nutrient-poor soil.',
    journalText:
      'Shore pine is the coastal form of lodgepole pine. It can survive where wind, salt spray, and poor soil keep many forest trees away.',
    sketchbookNote: 'Wind-shaped pine holding the sheltered edge.',
    spriteId: 'shore-pine',
    collectible: false,
  },
  'beach-strawberry': {
    id: 'beach-strawberry',
    commonName: 'Beach Strawberry',
    scientificName: 'Fragaria chiloensis',
    category: 'plant',
    shortFact: 'Beach strawberry spreads with runners, sending new plants across sandy ground.',
    journalText:
      'Beach strawberry is a low coastal plant with runners that creep outward and start new plants. Its fruits feed animals along dunes and scrub edges.',
    spriteId: 'beach-strawberry',
    collectible: true,
  },
  kinnikinnick: {
    id: 'kinnikinnick',
    commonName: 'Kinnikinnick',
    scientificName: 'Arctostaphylos uva-ursi',
    category: 'plant',
    shortFact: 'Kinnikinnick makes low evergreen mats beneath coastal pines and on sandy ground.',
    journalText:
      'Kinnikinnick is a low evergreen shrub that can spread in mats over sandy coastal soil. Beneath shore pines, it helps show ground that stays steadier and more sheltered than the open dune.',
    sketchbookNote: 'Evergreen mat tucked under wind-shaped shore pines.',
    spriteId: 'kinnikinnick',
    collectible: false,
  },
  'nootka-rose': nootkaRoseEntry,
  'salmonberry': salmonberryEntry,
  'sword-fern': swordFernEntry,
  'deer-mouse': {
    id: 'deer-mouse',
    commonName: 'Deer Mouse',
    scientificName: 'Peromyscus maniculatus',
    category: 'animal',
    shortFact: 'Deer mice eat many kinds of seeds and hide under plants or logs.',
    journalText:
      'A deer mouse is a small nighttime mammal that uses shrubs, grasses, and fallen wood for cover. It helps link plants and predators in many habitats.',
    spriteId: 'deer-mouse',
    collectible: false,
  },
  'song-sparrow': {
    id: 'song-sparrow',
    commonName: 'Song Sparrow',
    scientificName: 'Melospiza melodia',
    category: 'animal',
    shortFact: 'Song sparrows often stay low in shrubs where nests and cover are safer.',
    journalText:
      'Song sparrows are common birds of thickets, marsh edges, and brushy places. Dense shrubs give them perches, nest sites, and places to hide.',
    spriteId: 'song-sparrow',
    collectible: false,
  },
  'nurse-log': {
    id: 'nurse-log',
    commonName: 'Nurse Log',
    category: 'landmark',
    subtitle: 'Moist seedling bed',
    subtitleLabel: 'Habitat role',
    shortFact: 'A rotting log can hold water and give tiny plants a place to start.',
    journalText:
      'A nurse log is a fallen tree that slowly breaks down. It can stay moist, hold nutrients, and help seedlings begin life above the forest floor.',
    sketchbookNote: 'Soft old wood holding moisture for new starts.',
    spriteId: 'nurse-log',
    collectible: false,
  },
} satisfies BiomeDefinition['entries'];

export const coastalScrubBiome: BiomeDefinition = {
  id: 'coastal-scrub',
  name: 'Coastal Scrub',
  palette: coastalScrubPalette,
  tileSet: ['scrub-top', 'scrub-fill', 'drift-platform'],
  parallaxLayers: [
    { id: 'far-dune-ridge', speed: 0.16, color: '#cfbf8b', amplitude: 6, baseY: 80 },
    { id: 'scrub-band', speed: 0.32, color: '#7f9564', amplitude: 7, baseY: 92 },
  ],
  terrainRules: {
    worldWidth: 640,
    worldHeight: 144,
    sampleStep: 16,
    zones: [
      { id: 'back-dune', label: 'Back Dune', start: 0, end: 150, surfaceBaseY: 106, surfaceVariance: 6 },
      { id: 'shrub-thicket', label: 'Shrub Thicket', start: 150, end: 252, surfaceBaseY: 112, surfaceVariance: 4 },
      { id: 'windbreak-swale', label: 'Windbreak Swale', start: 252, end: 392, surfaceBaseY: 122, surfaceVariance: 3 },
      { id: 'shore-pine-stand', label: 'Shore Pine Stand', start: 392, end: 520, surfaceBaseY: 110, surfaceVariance: 5 },
      { id: 'forest-edge', label: 'Forest Edge', start: 520, end: 640, surfaceBaseY: 114, surfaceVariance: 4 },
    ],
    platformRules: [
      {
        id: 'thicket-root-step',
        zoneId: 'shrub-thicket',
        minCount: 1,
        maxCount: 2,
        minWidth: 18,
        maxWidth: 28,
        height: 4,
        liftMin: 8,
        liftMax: 13,
        spriteId: 'drift-platform',
      },
      {
        id: 'forest-log-rise',
        zoneId: 'forest-edge',
        minCount: 1,
        maxCount: 2,
        minWidth: 20,
        maxWidth: 28,
        height: 4,
        liftMin: 7,
        liftMax: 11,
        spriteId: 'drift-platform',
      },
    ],
    authoredPlatforms: [
      {
        id: 'windbreak-swale-entry-log',
        spriteId: 'drift-platform',
        x: 258,
        y: 107,
        w: 24,
        h: 4,
      },
      {
        id: 'windbreak-swale-upper-log',
        spriteId: 'drift-platform',
        x: 292,
        y: 100,
        w: 100,
        h: 4,
      },
      {
        id: 'windbreak-swale-exit-log',
        spriteId: 'drift-platform',
        x: 398,
        y: 105,
        w: 24,
        h: 4,
      },
    ],
  },
  spawnTables: [
    {
      id: 'stable-back-dune-grasses',
      zoneId: 'back-dune',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 22,
      entries: [
        { entryId: 'beach-grass', weight: 4 },
        { entryId: 'beach-pea', weight: 2 },
        { entryId: 'sand-verbena', weight: 3 },
        { entryId: 'sea-rocket', weight: 1 },
      ],
    },
    {
      id: 'stable-back-dune-runners',
      zoneId: 'back-dune',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [{ entryId: 'beach-pea', weight: 1 }],
    },
    {
      id: 'stable-back-dune-lupine',
      zoneId: 'back-dune',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 30,
      entries: [{ entryId: 'dune-lupine', weight: 1 }],
    },
    {
      id: 'stable-shrub-thicket',
      zoneId: 'shrub-thicket',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 24,
      entries: [
        { entryId: 'pacific-wax-myrtle', weight: 4 },
        { entryId: 'coyote-brush', weight: 3 },
        { entryId: 'dune-lupine', weight: 2 },
        { entryId: 'nootka-rose', weight: 2 },
      ],
    },
    {
      id: 'stable-shore-pines',
      zoneId: 'shore-pine-stand',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 32,
      entries: [{ entryId: 'shore-pine', weight: 1 }],
    },
    {
      id: 'stable-shore-pine-underlayer',
      zoneId: 'shore-pine-stand',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 22,
      entries: [{ entryId: 'kinnikinnick', weight: 1 }],
    },
    {
      id: 'stable-windbreak-swale',
      zoneId: 'windbreak-swale',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 24,
      entries: [
        { entryId: 'dune-lupine', weight: 3 },
        { entryId: 'beach-pea', weight: 1 },
        { entryId: 'pacific-wax-myrtle', weight: 3 },
        { entryId: 'coyote-brush', weight: 2 },
      ],
    },
    {
      id: 'stable-swale-runners',
      zoneId: 'windbreak-swale',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [{ entryId: 'beach-strawberry', weight: 1 }],
    },
    {
      id: 'stable-forest-edge-floor',
      zoneId: 'forest-edge',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 26,
      entries: [{ entryId: 'sword-fern', weight: 1 }],
    },
    {
      id: 'stable-forest-edge-thicket',
      zoneId: 'forest-edge',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [{ entryId: 'nootka-rose', weight: 1 }],
    },
    {
      id: 'stable-nurse-log',
      zoneId: 'forest-edge',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 12,
      entries: [{ entryId: 'nurse-log', weight: 1 }],
    },
    {
      id: 'salmonberry-patches',
      zoneId: 'forest-edge',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 20,
      entries: [{ entryId: 'salmonberry', weight: 1 }],
    },
    {
      id: 'strawberry-runners',
      zoneId: 'back-dune',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 22,
      entries: [{ entryId: 'beach-strawberry', weight: 1 }],
    },
    {
      id: 'thicket-life',
      zoneId: 'shrub-thicket',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 24,
      entries: [
        { entryId: 'deer-mouse', weight: 3 },
        { entryId: 'song-sparrow', weight: 2 },
      ],
    },
    {
      id: 'swale-cover-life',
      zoneId: 'windbreak-swale',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [
        { entryId: 'deer-mouse', weight: 3 },
        { entryId: 'song-sparrow', weight: 2 },
      ],
    },
    {
      id: 'pine-edge-birds',
      zoneId: 'shore-pine-stand',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 34,
      entries: [{ entryId: 'song-sparrow', weight: 1 }],
    },
  ],
  ambientRules: {
    cloudCount: [1, 3],
    sparkleCount: [8, 14],
  },
  entries: coastalScrubEntries,
  ecosystemNotes: [
    {
      id: 'pine-underlayer',
      title: 'Pine Underlayer',
      entryIds: ['shore-pine', 'kinnikinnick', 'song-sparrow'],
      minimumDiscoveries: 2,
      summary:
        'Under shore pines, low mats and quiet cover show sand that stays steadier than the open scrub behind.',
      observationPrompt:
        'Where does the scrub start feeling quieter?',
      zoneId: 'shore-pine-stand',
    },
    {
      id: 'thorny-cover',
      title: 'Thorny Cover',
      entryIds: ['nootka-rose', 'song-sparrow', 'deer-mouse'],
      minimumDiscoveries: 2,
      summary:
        'Thorny rose stems turn this scrub into safer cover for nests and quick hiding.',
      observationPrompt:
        'Where does the scrub feel safest to hide?',
      zoneId: 'shrub-thicket',
    },
    {
      id: 'sturdier-cover',
      title: 'Sturdier Cover',
      entryIds: ['dune-lupine', 'pacific-wax-myrtle', 'coyote-brush'],
      minimumDiscoveries: 3,
      summary:
        'Pioneer flowers give way to woody shrubs as the scrub starts holding steadier cover.',
      observationPrompt:
        'Which stems here feel built for steadier cover?',
      zoneId: 'windbreak-swale',
    },
    {
      id: 'shelter-builds-here',
      title: 'Shelter Builds Here',
      entryIds: ['beach-grass', 'sand-verbena', 'dune-lupine'],
      summary:
        'Dune plants slow wind and help harsh sand start holding more life.',
      observationPrompt:
        'Where does the scrub start looking calmer?',
      zoneId: 'back-dune',
    },
    {
      id: 'edge-moisture',
      title: 'Edge Moisture',
      entryIds: ['sword-fern', 'nurse-log', 'salmonberry'],
      minimumDiscoveries: 2,
      summary:
        'At the scrub edge, logs and berries mark cooler, wetter ground than the open dune behind.',
      observationPrompt:
        'Where does the ground start holding more shade?',
      zoneId: 'forest-edge',
    },
    {
      id: 'swale-shelter',
      title: 'Swale Shelter',
      entryIds: ['beach-strawberry', 'song-sparrow', 'pacific-wax-myrtle'],
      minimumDiscoveries: 2,
      summary:
        'Low runners and shrubs make calmer pockets in the swale, and birds use that cover fast.',
      observationPrompt:
        'Where does the swale feel calmer than the dune?',
      zoneId: 'windbreak-swale',
    },
    {
      id: 'thicket-cover',
      title: 'Thicket Cover',
      entryIds: ['pacific-wax-myrtle', 'coyote-brush', 'salmonberry', 'deer-mouse'],
      summary:
        'Shrubs and berries make food and hiding places as the scrub gets denser.',
      observationPrompt:
        'Where could a mouse hide fastest here?',
      zoneId: 'shrub-thicket',
    },
  ],
  phenology: {
    phases: {
      early: {
        skyWashTop: 'rgba(235, 238, 214, 0.10)',
        skyWashBottom: 'rgba(244, 238, 220, 0.06)',
        groundWash: 'rgba(212, 214, 156, 0.08)',
        entryAccents: [
          { entryId: 'sand-verbena', style: 'bloom', primaryColor: '#f4d36f', secondaryColor: '#fff3cb' },
          { entryId: 'dune-lupine', style: 'bloom', primaryColor: '#7b67cc', secondaryColor: '#d9ccff' },
        ],
      },
      peak: {
        skyWashTop: 'rgba(227, 238, 210, 0.08)',
        skyWashBottom: 'rgba(243, 239, 224, 0.05)',
        groundWash: 'rgba(160, 183, 110, 0.10)',
        entryAccents: [
          { entryId: 'beach-strawberry', style: 'berry', primaryColor: '#dc6057', secondaryColor: '#ffd7cf' },
          { entryId: 'salmonberry', style: 'berry', primaryColor: '#f09a48', secondaryColor: '#ffd8b3' },
        ],
        spawnEmphasis: [
          { tableId: 'strawberry-runners', minCountDelta: 1, maxCountDelta: 1 },
          { tableId: 'salmonberry-patches', maxCountDelta: 1 },
        ],
      },
      late: {
        skyWashTop: 'rgba(222, 210, 181, 0.09)',
        skyWashBottom: 'rgba(234, 225, 201, 0.06)',
        groundWash: 'rgba(170, 154, 98, 0.12)',
        entryAccents: [
          { entryId: 'sea-rocket', style: 'seed', primaryColor: '#cca06c', secondaryColor: '#f2d9b0' },
          { entryId: 'pacific-wax-myrtle', style: 'berry', primaryColor: '#4a536a', secondaryColor: '#aab3d0' },
        ],
      },
    },
  },
  processMoments: [
    {
      id: 'sand-capture',
      style: 'sand-drift',
      entryIds: ['beach-grass', 'dune-lupine', 'pacific-wax-myrtle'],
      zoneIds: ['back-dune', 'windbreak-swale'],
      minimumVisitCount: 2,
      phenologyPhases: ['late'],
      primaryColor: '#c79f62',
      secondaryColor: '#f1dfb2',
    },
  ],
  startPosition: {
    x: 26,
    y: 82,
  },
};
