import { forestPalette } from '../../assets/palette';
import type { BiomeDefinition } from '../../engine/types';
import { bunchberryEntry, nootkaRoseEntry, salmonberryEntry, swordFernEntry } from '../shared-entries';

const forestEntries = {
  'douglas-fir-sapling': {
    id: 'douglas-fir-sapling',
    commonName: 'Douglas-fir Sapling',
    scientificName: 'Pseudotsuga menziesii',
    category: 'plant',
    shortFact: 'Young Douglas-firs grow slowly in shade until a patch of sunlight reaches them.',
    journalText:
      'Douglas-fir trees can live for hundreds of years. A sapling waits for enough light, water, and space before it stretches upward into the canopy.',
    spriteId: 'douglas-fir-sapling',
    collectible: false,
  },
  'sword-fern': swordFernEntry,
  'redwood-sorrel': {
    id: 'redwood-sorrel',
    commonName: 'Redwood Sorrel',
    scientificName: 'Oxalis oregana',
    category: 'plant',
    shortFact: 'Redwood sorrel folds its leaves when sunlight gets too bright.',
    journalText:
      'Redwood sorrel likes cool, shady forests. Its clover-shaped leaves help it catch gentle light without drying out.',
    sketchbookNote: 'Cool clover leaves thickening the dim forest floor.',
    spriteId: 'redwood-sorrel',
    collectible: false,
  },
  'western-trillium': {
    id: 'western-trillium',
    commonName: 'Western Trillium',
    scientificName: 'Trillium ovatum',
    category: 'plant',
    shortFact: 'Western trillium likes rich, shady forest ground where the soil stays cool.',
    journalText:
      'Western trillium is a forest wildflower of moist Pacific woods. It grows on rich shady ground beneath bigger trees and shows how layered the forest floor can be.',
    spriteId: 'western-trillium',
    collectible: false,
  },
  'licorice-fern': {
    id: 'licorice-fern',
    commonName: 'Licorice Fern',
    scientificName: 'Polypodium glycyrrhiza',
    category: 'plant',
    shortFact: 'Licorice fern can grow on mossy trunks, logs, and rocks where rain keeps it damp.',
    journalText:
      'Licorice fern often grows above the ground on mossy bark, logs, or rocks in moist Pacific forests. Its creeping stem helps it spread across those damp surfaces.',
    spriteId: 'licorice-fern',
    collectible: false,
  },
  'tree-lungwort': {
    id: 'tree-lungwort',
    commonName: 'Tree Lungwort',
    scientificName: 'Lobaria pulmonaria',
    category: 'lichen',
    shortFact: 'Tree lungwort grows on damp trunks and mossy rocks, where it helps feed forest nutrient cycles.',
    journalText:
      'Tree lungwort is a leafy lichen of cool, humid forests. Because cyanobacteria live inside it, tree lungwort can help move nitrogen into the forest food web.',
    spriteId: 'tree-lungwort',
    collectible: false,
  },
  'old-mans-beard': {
    id: 'old-mans-beard',
    commonName: "Old-Man's-Beard Lichen",
    scientificName: 'Alectoria sarmentosa',
    category: 'lichen',
    shortFact: "Old-man's-beard hangs from cool forest branches where moist air helps it grow.",
    journalText:
      "Old-man's-beard is a stringy lichen that hangs from conifer branches in moist Pacific forests. Its pale strands show that one giant tree can hold life high above the darker forest floor.",
    sketchbookNote: 'Pale lichen trailing from the giant crown.',
    spriteId: 'old-mans-beard',
    collectible: false,
  },
  'western-hemlock-seedling': {
    id: 'western-hemlock-seedling',
    commonName: 'Western Hemlock Seedling',
    scientificName: 'Tsuga heterophylla',
    category: 'plant',
    shortFact: 'Western hemlock seedlings often start on rotten logs where damp wood holds water.',
    journalText:
      'Western hemlock can sprout on rotting logs and stumps in cool Pacific forests. The damp wood acts like a nursery, helping tiny roots start before they reach the soil below.',
    sketchbookNote: 'Tiny hemlock starting from damp old wood.',
    spriteId: 'western-hemlock-seedling',
    collectible: false,
  },
  bunchberry: bunchberryEntry,
  'salal-berry': {
    id: 'salal-berry',
    commonName: 'Salal Berry',
    scientificName: 'Gaultheria shallon',
    category: 'plant',
    shortFact: 'Salal berries feed birds and mammals that move seeds around the forest.',
    journalText:
      'Salal is a forest shrub with thick leaves and dark berries. Animals eat the fruit and help spread new salal plants to other places.',
    spriteId: 'salal-berry',
    collectible: true,
  },
  'nootka-rose': nootkaRoseEntry,
  'red-huckleberry': {
    id: 'red-huckleberry',
    commonName: 'Red Huckleberry',
    scientificName: 'Vaccinium parvifolium',
    category: 'plant',
    shortFact: 'Red huckleberry often grows from mossy logs or stumps on cool Pacific forest edges.',
    journalText:
      'Red huckleberry is a Pacific forest shrub with bright red berries. It often grows from old mossy logs or stumps where filtered light and moisture help it start.',
    sketchbookNote: 'Bright berries rising from mossy wood.',
    spriteId: 'red-huckleberry',
    collectible: true,
  },
  'salmonberry': salmonberryEntry,
  'fir-cone': {
    id: 'fir-cone',
    commonName: 'Douglas-fir Cone',
    scientificName: 'Pseudotsuga menziesii',
    category: 'plant',
    shortFact: 'Cone scales protect seeds until dry weather helps them open.',
    journalText:
      'A Douglas-fir cone holds seeds between its scales. When the cone dries out, the scales spread apart so wind can carry the seeds away.',
    spriteId: 'fir-cone',
    collectible: true,
  },
  'seep-stone': {
    id: 'seep-stone',
    commonName: 'Seep Stone',
    category: 'landmark',
    shortFact: 'A seep is a place where groundwater moves slowly through soil or rock and keeps the area damp.',
    journalText:
      'This under-root stone marks a slow seep where moisture keeps the lowest pocket cool and wet. Damp shelter spots like this help soft-bodied forest life stay active below the brighter trail.',
    sketchbookNote: 'Cool seep stone keeping the hollow wet.',
    subtitle: 'Slow groundwater seep',
    spriteId: 'seep-stone',
    collectible: false,
  },
  'seep-moss-mat': {
    id: 'seep-moss-mat',
    commonName: 'Seep Moss Mat',
    category: 'landmark',
    shortFact: 'Thin seep water can keep moss growing on rough stone even above the lowest wet pocket.',
    journalText:
      'This mossy patch clings to a seep wall where slow groundwater keeps rough stone damp. Small seep surfaces like this can hold moss and other tiny life above the wettest basin floor.',
    sketchbookNote: 'Wet seep moss holding to the hollow wall.',
    subtitle: 'Water-holding seep moss',
    spriteId: 'seep-moss-mat',
    collectible: false,
  },
  'fallen-giant-log': {
    id: 'fallen-giant-log',
    commonName: 'Fallen Giant Log',
    category: 'landmark',
    shortFact: 'A huge fallen log can keep shading moisture and sheltering life long after the tree comes down.',
    journalText:
      'This fallen giant log makes a gentle crossing between the damp hollow behind you and the old-growth pocket ahead. Even after a big tree falls, its bark and wood can still hold moisture, shade the ground, and shelter forest life.',
    sketchbookNote: 'One fallen giant still bridging damp forest layers.',
    subtitle: 'Old-wood crossing',
    spriteId: 'nurse-log',
    collectible: false,
  },
  'root-curtain': {
    id: 'root-curtain',
    commonName: 'Root Curtain',
    category: 'landmark',
    shortFact: 'Hanging roots can slow drips, hold bits of soil, and make shaded shelter above the cave floor.',
    journalText:
      'This curtain of roots hangs over the return shelf where dim light and damp bark still hold moisture. Root tangles like this can trap shade, droplets, and loose soil, making tiny shelter spots above the wettest pocket.',
    sketchbookNote: 'Dim root shelter catching drips above the cave.',
    subtitle: 'Hanging root shelter',
    spriteId: 'root-curtain',
    collectible: false,
  },
  'woodpecker-cavity': {
    id: 'woodpecker-cavity',
    commonName: 'Woodpecker Cavity',
    category: 'landmark',
    shortFact: 'A woodpecker cavity is a hole in bark or wood that can later shelter other forest life.',
    journalText:
      'Pileated woodpeckers chisel deep holes in softened wood while searching or nesting. Long after the bird moves on, one cavity can keep dry cover inside the giant trunk and add another shelter layer to old-growth forest.',
    sketchbookNote: 'Old bark hollow holding dry shelter in giant wood.',
    subtitle: 'Old shelter hole',
    spriteId: 'woodpecker-cavity',
    collectible: false,
  },
  'canopy-moss-bed': {
    id: 'canopy-moss-bed',
    commonName: 'Canopy Moss Bed',
    category: 'landmark',
    shortFact: 'Thick branch moss can hold water and bits of soil high above the forest floor.',
    journalText:
      'This mossy branch bed shows how an old limb can catch water, loose soil, and tiny plant starts. In giant wet forests, some branches become soft little gardens high above the ground.',
    sketchbookNote: 'Soft branch moss making a little treetop bed.',
    subtitle: 'Water-holding branch moss',
    spriteId: 'canopy-moss-bed',
    collectible: false,
  },
  ensatina: {
    id: 'ensatina',
    commonName: 'Ensatina Salamander',
    scientificName: 'Ensatina eschscholtzii',
    category: 'animal',
    shortFact: 'Ensatina salamanders hide in damp logs and rocks so their skin stays moist.',
    journalText:
      'An ensatina is a lungless salamander of shady forests. It spends much of its time tucked under logs, bark, or stones where moisture stays trapped.',
    sketchbookNote: 'Small salamander hiding in cool wet bark.',
    spriteId: 'ensatina',
    collectible: false,
  },
  'banana-slug': {
    id: 'banana-slug',
    commonName: 'Banana Slug',
    scientificName: 'Ariolimax columbianus',
    category: 'animal',
    shortFact: 'A banana slug stays moist with slime so its soft body does not dry out.',
    journalText:
      'Banana slugs help break down dead plants on the forest floor. That turns old leaves and wood into nutrients that other living things can use.',
    spriteId: 'banana-slug',
    collectible: false,
  },
  'steller-jay': {
    id: 'steller-jay',
    commonName: "Steller's Jay",
    scientificName: 'Cyanocitta stelleri',
    category: 'animal',
    shortFact: "Steller's jays use loud calls to warn other animals when danger is nearby.",
    journalText:
      "Steller's jays are clever forest birds with bright blue feathers and dark crests. They cache food and help spread some seeds when they forget a hiding spot.",
    spriteId: 'steller-jay',
    collectible: false,
  },
  'pileated-woodpecker': {
    id: 'pileated-woodpecker',
    commonName: 'Pileated Woodpecker',
    scientificName: 'Dryocopus pileatus',
    category: 'animal',
    shortFact: 'Pileated woodpeckers chisel dead wood to find carpenter ants and other insects.',
    journalText:
      'Pileated woodpeckers are big forest birds that hammer dead wood for insects and nesting holes. Their digging can leave cavities that other animals use later.',
    spriteId: 'pileated-woodpecker',
    collectible: false,
  },
} satisfies BiomeDefinition['entries'];

export const forestBiome: BiomeDefinition = {
  id: 'forest',
  name: 'Forest Trail',
  palette: forestPalette,
  tileSet: ['moss-top', 'soil-fill', 'log-platform'],
  parallaxLayers: [
    { id: 'far-ridge', speed: 0.14, color: '#90aa84', amplitude: 5, baseY: 72 },
    { id: 'tree-band', speed: 0.3, color: '#5b7d55', amplitude: 8, baseY: 88 },
  ],
  terrainRules: {
    worldWidth: 800,
    worldHeight: 336,
    sampleStep: 16,
    zones: [
      { id: 'trailhead', label: 'Trailhead', start: 0, end: 150, surfaceBaseY: 110, surfaceVariance: 4 },
      { id: 'fern-hollow', label: 'Fern Hollow', start: 150, end: 280, surfaceBaseY: 116, surfaceVariance: 5 },
      { id: 'root-hollow', label: 'Root Hollow', start: 280, end: 344, surfaceBaseY: 150, surfaceVariance: 4 },
      { id: 'seep-pocket', label: 'Seep Pocket', start: 344, end: 360, surfaceBaseY: 184, surfaceVariance: 3 },
      { id: 'stone-basin', label: 'Stone Basin', start: 360, end: 392, surfaceBaseY: 236, surfaceVariance: 2 },
      { id: 'filtered-return', label: 'Filtered Return', start: 392, end: 432, surfaceBaseY: 162, surfaceVariance: 3 },
      { id: 'log-run', label: 'Log Run', start: 432, end: 520, surfaceBaseY: 118, surfaceVariance: 4 },
      { id: 'creek-bend', label: 'Creek Bend', start: 520, end: 620, surfaceBaseY: 116, surfaceVariance: 6 },
      { id: 'old-growth-pocket', label: 'Old-Growth Pocket', start: 620, end: 728, surfaceBaseY: 172, surfaceVariance: 6 },
      { id: 'old-growth-rise', label: 'Old-Growth Rise', start: 728, end: 800, surfaceBaseY: 122, surfaceVariance: 4 },
    ],
    platformRules: [
      {
        id: 'fallen-log',
        zoneId: 'fern-hollow',
        minCount: 1,
        maxCount: 2,
        minWidth: 18,
        maxWidth: 30,
        height: 4,
        liftMin: 8,
        liftMax: 14,
        spriteId: 'log-platform',
      },
      {
        id: 'creek-log',
        zoneId: 'creek-bend',
        minCount: 1,
        maxCount: 2,
        minWidth: 16,
        maxWidth: 24,
        height: 4,
        liftMin: 7,
        liftMax: 11,
        spriteId: 'log-platform',
      },
    ],
    authoredPlatforms: [
      {
        id: 'root-hollow-entry-log',
        spriteId: 'log-platform',
        x: 286,
        y: 128,
        w: 24,
        h: 4,
      },
      {
        id: 'root-hollow-mid-ledge',
        spriteId: 'rock-platform',
        x: 318,
        y: 108,
        w: 92,
        h: 4,
      },
      {
        id: 'root-hollow-cave-sill',
        spriteId: 'rock-platform',
        x: 346,
        y: 154,
        w: 30,
        h: 4,
      },
      {
        id: 'root-hollow-basin-sill',
        spriteId: 'rock-platform',
        x: 382,
        y: 194,
        w: 26,
        h: 4,
      },
      {
        id: 'root-hollow-return-nook',
        spriteId: 'rock-platform',
        x: 368,
        y: 96,
        w: 36,
        h: 4,
      },
      {
        id: 'root-hollow-high-ledge',
        spriteId: 'rock-platform',
        x: 400,
        y: 88,
        w: 28,
        h: 4,
      },
      {
        id: 'filtered-return-mouth-sill',
        spriteId: 'rock-platform',
        x: 406,
        y: 104,
        w: 18,
        h: 4,
      },
      {
        id: 'root-hollow-exit-log',
        spriteId: 'log-platform',
        x: 430,
        y: 116,
        w: 24,
        h: 4,
      },
      {
        id: 'log-run-high-run-log',
        spriteId: 'log-platform',
        x: 444,
        y: 100,
        w: 68,
        h: 4,
      },
      {
        id: 'creek-bend-high-run-log',
        spriteId: 'log-platform',
        x: 514,
        y: 98,
        w: 62,
        h: 4,
      },
      {
        id: 'old-growth-root-log',
        spriteId: 'log-platform',
        x: 640,
        y: 152,
        w: 28,
        h: 4,
      },
      {
        id: 'old-growth-trunk-foot-rest',
        spriteId: 'log-platform',
        x: 662,
        y: 144,
        w: 24,
        h: 4,
      },
      {
        id: 'old-growth-crossover-limb',
        spriteId: 'log-platform',
        x: 650,
        y: 106,
        w: 36,
        h: 4,
      },
      {
        id: 'old-growth-crown-window',
        spriteId: 'log-platform',
        x: 688,
        y: 24,
        w: 28,
        h: 4,
      },
      {
        id: 'forest-layer-bridge-log',
        spriteId: 'log-platform',
        x: 580,
        y: 98,
        w: 36,
        h: 4,
      },
      {
        id: 'forest-layer-bridge-span',
        spriteId: 'log-platform',
        x: 614,
        y: 106,
        w: 38,
        h: 4,
      },
      {
        id: 'old-wood-hinge-rest',
        spriteId: 'log-platform',
        x: 632,
        y: 130,
        w: 24,
        h: 4,
      },
      {
        id: 'old-growth-bark-shelf',
        spriteId: 'log-platform',
        x: 674,
        y: 118,
        w: 60,
        h: 4,
      },
      {
        id: 'old-growth-inner-bark-rest',
        spriteId: 'log-platform',
        x: 690,
        y: 58,
        w: 42,
        h: 4,
      },
      {
        id: 'old-growth-high-perch',
        spriteId: 'log-platform',
        x: 688,
        y: 36,
        w: 34,
        h: 4,
      },
      {
        id: 'old-growth-inner-loop-step',
        spriteId: 'log-platform',
        x: 700,
        y: 46,
        w: 26,
        h: 4,
      },
      {
        id: 'canopy-inner-rest-crook',
        spriteId: 'log-platform',
        x: 722,
        y: 50,
        w: 18,
        h: 4,
      },
      {
        id: 'old-growth-crown-rest',
        spriteId: 'log-platform',
        x: 648,
        y: 14,
        w: 32,
        h: 4,
      },
      {
        id: 'old-growth-canopy-ledge',
        spriteId: 'log-platform',
        x: 744,
        y: 58,
        w: 34,
        h: 4,
      },
    ],
    authoredDepthFeatures: [
      {
        id: 'root-hollow-root-arch',
        style: 'root-chamber',
        x: 284,
        y: 64,
        w: 148,
        h: 170,
      },
      {
        id: 'root-hollow-stone-basin',
        style: 'stone-pocket',
        x: 360,
        y: 186,
        w: 56,
        h: 66,
      },
      {
        id: 'root-hollow-under-basin-pocket',
        style: 'stone-pocket',
        x: 356,
        y: 208,
        w: 32,
        h: 40,
      },
      {
        id: 'root-hollow-filtered-pocket',
        style: 'root-chamber',
        x: 372,
        y: 100,
        w: 60,
        h: 104,
      },
      {
        id: 'old-growth-trunk-interior',
        style: 'trunk-interior',
        x: 658,
        y: 56,
        w: 68,
        h: 134,
      },
      {
        id: 'old-growth-trunk-foot-pocket',
        style: 'trunk-interior',
        x: 662,
        y: 124,
        w: 38,
        h: 58,
      },
      {
        id: 'old-growth-canopy-pocket',
        style: 'canopy-pocket',
        x: 648,
        y: 6,
        w: 148,
        h: 112,
      },
    ],
    authoredClimbables: [
      {
        id: 'root-hollow-fir-trunk',
        spriteId: 'climb-trunk',
        canopySpriteId: 'climb-canopy',
        x: 332,
        y: 46,
        w: 8,
        h: 108,
        topExitY: 98,
      },
      {
        id: 'root-hollow-cave-trunk',
        spriteId: 'climb-trunk',
        x: 404,
        y: 38,
        w: 8,
        h: 186,
        topExitY: 78,
      },
      {
        id: 'log-run-fir-trunk',
        spriteId: 'climb-trunk',
        canopySpriteId: 'climb-canopy',
        x: 446,
        y: 56,
        w: 8,
        h: 74,
        topExitY: 96,
      },
      {
        id: 'old-growth-main-trunk',
        spriteId: 'climb-trunk',
        canopySpriteId: 'giant-canopy',
        x: 686,
        y: 36,
        w: 24,
        h: 158,
        topExitY: 108,
      },
      {
        id: 'old-growth-inner-bark-snag',
        spriteId: 'climb-trunk',
        x: 678,
        y: 18,
        w: 8,
        h: 30,
        topExitY: 18,
      },
      {
        id: 'old-growth-crown-snag',
        spriteId: 'climb-trunk',
        canopySpriteId: 'giant-canopy',
        x: 680,
        y: 10,
        w: 8,
        h: 30,
        topExitY: 4,
      },
      {
        id: 'old-growth-upper-snag',
        spriteId: 'climb-trunk',
        x: 736,
        y: 44,
        w: 8,
        h: 82,
        topExitY: 48,
      },
      {
        id: 'old-growth-canopy-rung',
        spriteId: 'climb-trunk',
        x: 708,
        y: 28,
        w: 8,
        h: 42,
        topExitY: 26,
      },
    ],
    authoredEntities: [
      {
        id: 'root-hollow-licorice-trunk',
        entryId: 'licorice-fern',
        x: 324,
        y: 118,
        castsShadow: false,
      },
      {
        id: 'root-hollow-seep-lungwort',
        entryId: 'tree-lungwort',
        x: 350,
        y: 148,
        castsShadow: false,
      },
      {
        id: 'root-hollow-seep-stone',
        entryId: 'seep-stone',
        x: 356,
        y: 172,
      },
      {
        id: 'root-hollow-basin-ensatina',
        entryId: 'ensatina',
        x: 380,
        y: 220,
      },
      {
        id: 'root-hollow-basin-slug',
        entryId: 'banana-slug',
        x: 394,
        y: 218,
      },
      {
        id: 'root-hollow-pocket-lungwort',
        entryId: 'tree-lungwort',
        x: 366,
        y: 222,
        castsShadow: false,
      },
      {
        id: 'root-hollow-under-basin-moss',
        entryId: 'seep-moss-mat',
        x: 374,
        y: 194,
        castsShadow: false,
      },
      {
        id: 'root-hollow-lungwort-mid-ledge',
        entryId: 'tree-lungwort',
        x: 384,
        y: 100,
        castsShadow: false,
      },
      {
        id: 'root-hollow-return-sorrel',
        entryId: 'redwood-sorrel',
        x: 402,
        y: 150,
      },
      {
        id: 'filtered-return-root-curtain',
        entryId: 'root-curtain',
        x: 414,
        y: 124,
        castsShadow: false,
      },
      {
        id: 'filtered-return-lungwort-high',
        entryId: 'tree-lungwort',
        x: 380,
        y: 88,
        castsShadow: false,
      },
      {
        id: 'filtered-return-seep-moss',
        entryId: 'seep-moss-mat',
        x: 394,
        y: 136,
        castsShadow: false,
      },
      {
        id: 'filtered-return-mouth-moss',
        entryId: 'seep-moss-mat',
        x: 408,
        y: 104,
        castsShadow: false,
      },
      {
        id: 'root-hollow-licorice-high-ledge',
        entryId: 'licorice-fern',
        x: 410,
        y: 76,
      },
      {
        id: 'log-run-licorice-trunk',
        entryId: 'licorice-fern',
        x: 438,
        y: 90,
        castsShadow: false,
      },
      {
        id: 'old-growth-sorrel-base',
        entryId: 'redwood-sorrel',
        x: 640,
        y: 164,
      },
      {
        id: 'old-growth-bunchberry-floor',
        entryId: 'bunchberry',
        x: 650,
        y: 162,
      },
      {
        id: 'forest-layer-bridge-landmark',
        entryId: 'fallen-giant-log',
        x: 606,
        y: 100,
      },
      {
        id: 'old-growth-bridge-hemlock',
        entryId: 'western-hemlock-seedling',
        x: 620,
        y: 88,
      },
      {
        id: 'forest-layer-bridge-lungwort',
        entryId: 'tree-lungwort',
        x: 632,
        y: 104,
        castsShadow: false,
      },
      {
        id: 'old-wood-hinge-lungwort',
        entryId: 'tree-lungwort',
        x: 644,
        y: 126,
        castsShadow: false,
      },
      {
        id: 'old-growth-huckleberry-base',
        entryId: 'red-huckleberry',
        x: 656,
        y: 152,
      },
      {
        id: 'old-growth-trunk-foot-hemlock',
        entryId: 'western-hemlock-seedling',
        x: 674,
        y: 136,
      },
      {
        id: 'old-growth-crown-beard',
        entryId: 'old-mans-beard',
        x: 672,
        y: 14,
        castsShadow: false,
      },
      {
        id: 'old-growth-crown-window-lungwort',
        entryId: 'tree-lungwort',
        x: 666,
        y: 24,
        castsShadow: false,
      },
      {
        id: 'old-growth-crown-window-moss',
        entryId: 'canopy-moss-bed',
        x: 680,
        y: 22,
        castsShadow: false,
      },
      {
        id: 'old-growth-licorice-bark',
        entryId: 'licorice-fern',
        x: 694,
        y: 106,
        castsShadow: false,
      },
      {
        id: 'old-growth-woodpecker-cavity',
        entryId: 'woodpecker-cavity',
        x: 702,
        y: 132,
        castsShadow: false,
      },
      {
        id: 'old-growth-rise-hemlock',
        entryId: 'western-hemlock-seedling',
        x: 736,
        y: 108,
      },
      {
        id: 'old-growth-inner-rest-lungwort',
        entryId: 'tree-lungwort',
        x: 724,
        y: 54,
        castsShadow: false,
      },
      {
        id: 'old-growth-inner-rest-moss',
        entryId: 'canopy-moss-bed',
        x: 734,
        y: 44,
        castsShadow: false,
      },
      {
        id: 'old-growth-high-beard',
        entryId: 'old-mans-beard',
        x: 754,
        y: 46,
        castsShadow: false,
      },
      {
        id: 'canopy-inner-rest-beard',
        entryId: 'old-mans-beard',
        x: 740,
        y: 38,
        castsShadow: false,
      },
      {
        id: 'old-growth-high-licorice',
        entryId: 'licorice-fern',
        x: 700,
        y: 30,
        castsShadow: false,
      },
      {
        id: 'old-growth-crown-lungwort',
        entryId: 'tree-lungwort',
        x: 660,
        y: 10,
        castsShadow: false,
      },
      {
        id: 'old-growth-lungwort-high',
        entryId: 'tree-lungwort',
        x: 748,
        y: 74,
        castsShadow: false,
      },
      {
        id: 'old-growth-woodpecker-perch',
        entryId: 'pileated-woodpecker',
        x: 764,
        y: 64,
      },
    ],
  },
  spawnTables: [
    {
      id: 'stable-saplings',
      zoneId: 'trailhead',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 34,
      entries: [{ entryId: 'douglas-fir-sapling', weight: 1 }],
    },
    {
      id: 'stable-trailhead-thicket',
      zoneId: 'trailhead',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [{ entryId: 'nootka-rose', weight: 1 }],
    },
    {
      id: 'stable-forest-floor',
      zoneId: 'fern-hollow',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 24,
      entries: [
        { entryId: 'sword-fern', weight: 4 },
        { entryId: 'redwood-sorrel', weight: 3 },
      ],
    },
    {
      id: 'stable-fern-edge-rose',
      zoneId: 'fern-hollow',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 28,
      entries: [{ entryId: 'nootka-rose', weight: 1 }],
    },
    {
      id: 'stable-shade-flowers',
      zoneId: 'fern-hollow',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 30,
      entries: [{ entryId: 'western-trillium', weight: 1 }],
    },
    {
      id: 'stable-creek-floor',
      zoneId: 'creek-bend',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 24,
      entries: [
        { entryId: 'redwood-sorrel', weight: 4 },
        { entryId: 'sword-fern', weight: 2 },
        { entryId: 'bunchberry', weight: 2 },
        { entryId: 'western-trillium', weight: 1 },
      ],
    },
    {
      id: 'stable-old-growth-floor',
      zoneId: 'old-growth-pocket',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 22,
      entries: [
        { entryId: 'redwood-sorrel', weight: 4 },
        { entryId: 'sword-fern', weight: 2 },
        { entryId: 'bunchberry', weight: 2 },
      ],
    },
    {
      id: 'forest-cones',
      zoneId: 'log-run',
      refreshPolicy: 'visit',
      minCount: 3,
      maxCount: 4,
      spacing: 16,
      entries: [{ entryId: 'fir-cone', weight: 1 }],
    },
    {
      id: 'root-hollow-floor',
      zoneId: 'root-hollow',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 22,
      entries: [
        { entryId: 'sword-fern', weight: 4 },
        { entryId: 'redwood-sorrel', weight: 3 },
      ],
    },
    {
      id: 'root-hollow-life',
      zoneId: 'root-hollow',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [
        { entryId: 'banana-slug', weight: 3 },
        { entryId: 'ensatina', weight: 1 },
      ],
    },
    {
      id: 'seep-pocket-floor',
      zoneId: 'seep-pocket',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 24,
      entries: [{ entryId: 'sword-fern', weight: 1 }],
    },
    {
      id: 'seep-pocket-life',
      zoneId: 'seep-pocket',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 1,
      spacing: 24,
      entries: [
        { entryId: 'banana-slug', weight: 2 },
        { entryId: 'ensatina', weight: 1 },
      ],
    },
    {
      id: 'filtered-return-floor',
      zoneId: 'filtered-return',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 22,
      entries: [
        { entryId: 'redwood-sorrel', weight: 3 },
        { entryId: 'sword-fern', weight: 1 },
      ],
    },
    {
      id: 'trailhead-berries',
      zoneId: 'trailhead',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 26,
      entries: [
        { entryId: 'red-huckleberry', weight: 3 },
        { entryId: 'salmonberry', weight: 1 },
      ],
    },
    {
      id: 'berry-patches',
      zoneId: 'fern-hollow',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 22,
      entries: [{ entryId: 'salal-berry', weight: 1 }],
    },
    {
      id: 'fern-edge-berries',
      zoneId: 'fern-hollow',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'red-huckleberry', weight: 1 }],
    },
    {
      id: 'creek-berries',
      zoneId: 'creek-bend',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'salmonberry', weight: 1 }],
    },
    {
      id: 'old-growth-berries',
      zoneId: 'old-growth-pocket',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 1,
      spacing: 24,
      entries: [{ entryId: 'red-huckleberry', weight: 1 }],
    },
    {
      id: 'canopy-life',
      zoneId: 'trailhead',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 40,
      entries: [{ entryId: 'steller-jay', weight: 1 }],
    },
    {
      id: 'forest-floor-life',
      zoneId: 'creek-bend',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 28,
      entries: [
        { entryId: 'banana-slug', weight: 4 },
        { entryId: 'steller-jay', weight: 1 },
      ],
    },
    {
      id: 'woodpecker-canopy',
      zoneId: 'log-run',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 40,
      entries: [{ entryId: 'pileated-woodpecker', weight: 1 }],
    },
  ],
  ambientRules: {
    cloudCount: [1, 2],
    sparkleCount: [6, 12],
  },
  entries: forestEntries,
  ecosystemNotes: [
    {
      id: 'edge-berry-thicket',
      title: 'Edge Berry Thicket',
      entryIds: ['nootka-rose', 'red-huckleberry', 'salmonberry'],
      minimumDiscoveries: 2,
      summary:
        'The first forest edge stacks thorny stems and berries into a shadier thicket than the scrub behind.',
      observationPrompt:
        'Where does the first berry thicket gather?',
      zoneId: 'trailhead',
    },
    {
      id: 'forest-floor-recycling',
      title: 'Forest Floor Cycle',
      entryIds: ['banana-slug', 'sword-fern', 'western-trillium', 'douglas-fir-sapling'],
      summary:
        'Broken leaves feed soil for ferns and young trees.',
      observationPrompt:
        'What shows dead leaves feeding soil?',
      zoneId: 'root-hollow',
    },
    {
      id: 'hollow-moisture',
      title: 'Hollow Moisture',
      entryIds: ['licorice-fern', 'tree-lungwort', 'ensatina'],
      minimumDiscoveries: 2,
      summary:
        'Cool bark, rock, and logs make tiny wet shelters above the soil.',
      observationPrompt:
        'What here seems to hold moisture off the ground?',
      zoneId: 'root-hollow',
    },
    {
      id: 'seep-shelter',
      title: 'Seep Shelter',
      entryIds: ['seep-stone', 'banana-slug', 'ensatina'],
      minimumDiscoveries: 2,
      summary:
        'Slow seep water keeps the lowest pocket damp enough for soft-bodied forest life.',
      observationPrompt:
        'What here seems kept wet by seep water, not rain?',
      zoneId: 'stone-basin',
    },
    {
      id: 'root-held-shelter',
      title: 'Root-Held Shelter',
      entryIds: ['root-curtain', 'licorice-fern', 'tree-lungwort'],
      minimumDiscoveries: 2,
      summary:
        'Hanging roots and bark can keep damp shelter above the seep floor.',
      observationPrompt:
        'What here keeps moisture above the seep floor?',
      zoneId: 'filtered-return',
    },
    {
      id: 'seep-wall-garden',
      title: 'Seep Wall Garden',
      entryIds: ['seep-moss-mat', 'seep-stone', 'tree-lungwort'],
      minimumDiscoveries: 2,
      summary:
        'Seep water can keep moss and lichen clinging right on rough stone walls.',
      observationPrompt:
        'What here seems growing right on wet stone?',
      zoneId: 'stone-basin',
    },
    {
      id: 'forest-seed-travel',
      title: 'Seed Travel',
      entryIds: ['salal-berry', 'fir-cone', 'steller-jay'],
      summary:
        'Some forest seeds ride the wind, while others move with animals.',
      observationPrompt:
        'Which seeds seem ready to travel?',
      zoneId: 'log-run',
    },
    {
      id: 'creekside-shelter',
      title: 'Creekside Shelter',
      entryIds: ['salmonberry', 'redwood-sorrel', 'sword-fern'],
      minimumDiscoveries: 2,
      summary:
        'At wetter forest edges, berries and low leaves show where cool cover still holds.',
      observationPrompt:
        'What here looks held by cool, wet cover?',
      zoneId: 'creek-bend',
    },
    {
      id: 'old-wood-nursery',
      title: 'Old-Wood Nursery',
      entryIds: ['fallen-giant-log', 'western-hemlock-seedling'],
      minimumDiscoveries: 2,
      summary:
        'Old wood can hold enough water and shade for a new tree to start above the soil.',
      observationPrompt:
        'What here looks like old wood growing a new tree?',
    },
    {
      id: 'old-wood-link',
      title: 'Old Wood Link',
      entryIds: ['fallen-giant-log', 'seep-stone', 'woodpecker-cavity'],
      minimumDiscoveries: 3,
      summary:
        'One old forest can connect seep shelter below with old-wood shelter higher up.',
      observationPrompt:
        'What hints that hollow shelter connects upward?',
      zoneId: 'creek-bend',
    },
    {
      id: 'old-growth-bark-life',
      title: 'Hanging Bark Life',
      entryIds: ['old-mans-beard', 'tree-lungwort', 'woodpecker-cavity'],
      minimumDiscoveries: 2,
      summary:
        'One giant tree can hold hanging lichens, bark life, and dry shelter holes in separate layers.',
      observationPrompt:
        'What here hangs, clings, or shelters on bark?',
      zoneId: 'old-growth-pocket',
    },
    {
      id: 'forests-above',
      title: 'Forests Above',
      entryIds: ['canopy-moss-bed', 'old-mans-beard', 'western-hemlock-seedling'],
      minimumDiscoveries: 2,
      summary:
        'One giant branch can hold enough moss and water for a tiny forest to begin above the ground.',
      observationPrompt:
        'What here looks like a little forest above?',
      zoneId: 'old-growth-pocket',
    },
    {
      id: 'forest-floor-carpet',
      title: 'Forest Floor Carpet',
      entryIds: ['bunchberry', 'redwood-sorrel', 'western-hemlock-seedling'],
      minimumDiscoveries: 2,
      summary:
        'Even near the last big trees, cool shade still stacks low leaves and tiny starts into a full forest floor.',
      observationPrompt:
        'What here still looks like a full forest floor?',
      zoneId: 'old-growth-pocket',
    },
  ],
  verticalCues: [
    {
      id: 'stone-basin-return-light',
      style: 'recovery-light',
      x: 390,
      y: 92,
      zoneIds: ['seep-pocket', 'stone-basin', 'filtered-return'],
    },
    {
      id: 'old-wood-hinge-light',
      style: 'recovery-light',
      x: 654,
      y: 122,
      zoneIds: ['old-growth-pocket'],
    },
    {
      id: 'old-growth-inner-rest-light',
      style: 'canopy-opening',
      x: 724,
      y: 46,
      zoneIds: ['old-growth-pocket'],
    },
  ],
  phenology: {
    phases: {
      early: {
        skyWashTop: 'rgba(231, 240, 224, 0.10)',
        skyWashBottom: 'rgba(239, 243, 232, 0.05)',
        groundWash: 'rgba(122, 150, 96, 0.08)',
        parallaxColors: ['#9daf90', '#5f835c'],
        entryAccents: [
          { entryId: 'western-trillium', style: 'bloom', primaryColor: '#fff8e5', secondaryColor: '#f6d687' },
        ],
      },
      peak: {
        skyWashTop: 'rgba(219, 233, 205, 0.06)',
        skyWashBottom: 'rgba(231, 239, 226, 0.05)',
        groundWash: 'rgba(110, 156, 96, 0.10)',
        parallaxColors: ['#98ad8e', '#5f875a'],
        entryAccents: [
          { entryId: 'salal-berry', style: 'berry', primaryColor: '#43589a', secondaryColor: '#b3bff1' },
        ],
        spawnEmphasis: [{ tableId: 'berry-patches', maxCountDelta: 1 }],
      },
      late: {
        skyWashTop: 'rgba(214, 202, 172, 0.10)',
        skyWashBottom: 'rgba(227, 221, 196, 0.05)',
        groundWash: 'rgba(144, 114, 78, 0.12)',
        parallaxColors: ['#9f977d', '#596d4b'],
        entryAccents: [
          { entryId: 'fir-cone', style: 'cone', primaryColor: '#8a5731', secondaryColor: '#d8b07e' },
          { entryId: 'salal-berry', style: 'berry', primaryColor: '#57417c', secondaryColor: '#c3b3df' },
        ],
        spawnEmphasis: [{ tableId: 'forest-cones', minCountDelta: 1, maxCountDelta: 1 }],
      },
    },
  },
  processMoments: [
    {
      id: 'moisture-hold',
      style: 'moisture-hold',
      entryIds: ['sword-fern', 'redwood-sorrel', 'salmonberry'],
      zoneIds: ['root-hollow', 'creek-bend'],
      minimumVisitCount: 2,
      weatherProfiles: ['mist-drip'],
      phenologyPhases: ['late'],
      primaryColor: '#4f6658',
      secondaryColor: '#d2e6d8',
    },
  ],
  startPosition: {
    x: 26,
    y: 82,
  },
};
