import { treelinePalette } from '../../assets/palette';
import type { BiomeDefinition } from '../../engine/types';
import {
  arcticWillowEntry,
  bunchberryEntry,
  crowberryEntry,
  lingonberryEntry,
  mossCampionEntry,
  mountainAvensEntry,
  reindeerLichenEntry,
} from '../shared-entries';

const treelineEntries = {
  'mountain-hemlock': {
    id: 'mountain-hemlock',
    commonName: 'Mountain Hemlock',
    scientificName: 'Tsuga mertensiana',
    category: 'plant',
    shortFact: 'Mountain hemlock grows slowly on cold, snowy slopes near treeline.',
    journalText:
      'Mountain hemlock is a hardy evergreen of high mountains. Heavy snow and short summers slow its growth as it nears treeline.',
    spriteId: 'mountain-hemlock',
    collectible: false,
  },
  'dwarf-birch': {
    id: 'dwarf-birch',
    commonName: 'Dwarf Birch',
    scientificName: 'Betula nana',
    category: 'plant',
    shortFact: 'Dwarf birch stays low where cold wind is too harsh for tall trees.',
    journalText:
      'Dwarf birch is a tiny woody shrub of cold open ground. Low branches help it avoid the strongest wind above treeline.',
    sketchbookNote: 'Low birch holding where bright wind reaches last trees.',
    spriteId: 'dwarf-birch',
    collectible: false,
  },
  'bog-blueberry': {
    id: 'bog-blueberry',
    commonName: 'Bog Blueberry',
    scientificName: 'Vaccinium uliginosum',
    category: 'plant',
    shortFact: 'Bog blueberry is a low shrub that can grow from bogs up to alpine slopes.',
    journalText:
      'Bog blueberry grows in cold, acidic ground from wet flats to alpine slopes. Its berries feed animals during the short mountain summer.',
    spriteId: 'bog-blueberry',
    collectible: true,
  },
  bunchberry: bunchberryEntry,
  lingonberry: lingonberryEntry,
  'mountain-avens': mountainAvensEntry,
  'moss-campion': mossCampionEntry,
  'white-arctic-mountain-heather': {
    id: 'white-arctic-mountain-heather',
    commonName: 'White Arctic Mountain Heather',
    scientificName: 'Cassiope tetragona',
    category: 'plant',
    shortFact: 'White arctic mountain heather forms low mats that help protect tiny stems from alpine wind.',
    journalText:
      'White arctic mountain heather is a low heath plant of arctic-alpine ground. Its tight mat of tiny stems helps it stay close to calmer air near the soil.',
    sketchbookNote: 'Tight mats staying low beneath alpine wind.',
    spriteId: 'white-arctic-mountain-heather',
    collectible: false,
  },
  'reindeer-lichen': reindeerLichenEntry,
  'arctic-willow': arcticWillowEntry,
  crowberry: crowberryEntry,
  'rock-ptarmigan': {
    id: 'rock-ptarmigan',
    commonName: 'Rock Ptarmigan',
    scientificName: 'Lagopus muta',
    category: 'animal',
    shortFact: 'Rock ptarmigan nest on stony tundra where rocks help break the wind.',
    journalText:
      'Rock ptarmigan live on high open ground with stones, low plants, and snow. Their ground nests tuck into rocky tundra near shelter.',
    spriteId: 'rock-ptarmigan',
    collectible: false,
  },
  ermine: {
    id: 'ermine',
    commonName: 'Ermine',
    scientificName: 'Mustela erminea',
    category: 'animal',
    shortFact: 'An ermine can slip between rocks and shrubs to hunt small animals.',
    journalText:
      'An ermine is a quick predator with a long body made for weaving through rocks and low shrubs. In snowy seasons, many turn white for camouflage.',
    spriteId: 'ermine',
    collectible: false,
  },
  'hoary-marmot': {
    id: 'hoary-marmot',
    commonName: 'Hoary Marmot',
    scientificName: 'Marmota caligata',
    category: 'animal',
    shortFact: 'Hoary marmots whistle loudly when danger appears on open mountain slopes.',
    journalText:
      'Hoary marmots live among rocks on high mountain slopes near treeline. They use boulders for shelter and give sharp warning whistles when danger is near.',
    spriteId: 'hoary-marmot',
    collectible: false,
  },
  'krummholz-spruce': {
    id: 'krummholz-spruce',
    commonName: 'Krummholz Spruce',
    category: 'landmark',
    subtitle: 'Wind-shaped treeline',
    subtitleLabel: 'Habitat role',
    shortFact: 'Strong wind can keep treeline spruce low, crooked, and shrubby.',
    journalText:
      'Krummholz is the name for trees bent and stunted by cold wind near treeline. They show how harsh weather can reshape growth.',
    sketchbookNote: 'Wind-bent spruce showing where treeline gives way.',
    spriteId: 'krummholz-spruce',
    collectible: false,
  },
  'frost-heave-boulder': {
    id: 'frost-heave-boulder',
    commonName: 'Frost-Heave Boulder',
    category: 'landmark',
    subtitle: 'Freeze-and-lift stone',
    subtitleLabel: 'Ground process',
    shortFact: 'Freezing and thawing ground can slowly push big stones upward.',
    journalText:
      'A frost-heave boulder is moved by ground that freezes, swells, and thaws again. Cold landscapes can shift rocks without any animal lifting them.',
    sketchbookNote: 'Lifted stone showing freeze-thaw ground at work.',
    spriteId: 'frost-heave-boulder',
    collectible: false,
  },
  'talus-cushion-pocket': {
    id: 'talus-cushion-pocket',
    commonName: 'Talus Cushion Pocket',
    category: 'landmark',
    subtitle: 'Rock-sheltered alpine patch',
    subtitleLabel: 'Habitat role',
    shortFact: 'Sheltered gaps between alpine rocks can hold tiny cushions of life.',
    journalText:
      'A talus cushion pocket is a small sheltered patch between alpine stones. Windbreaks from the rocks help cushion plants and lichens keep a foothold on exposed ground.',
    sketchbookNote: 'Tiny shelter pocket holding on between alpine stones.',
    spriteId: 'talus-cushion-pocket',
    collectible: false,
  },
} satisfies BiomeDefinition['entries'];

export const treelineBiome: BiomeDefinition = {
  id: 'treeline',
  name: 'Treeline Pass',
  palette: treelinePalette,
  tileSet: ['treeline-top', 'treeline-fill', 'granite-platform'],
  parallaxLayers: [
    { id: 'far-alpine-ridge', speed: 0.12, color: '#cfd7db', amplitude: 4, baseY: 72 },
    { id: 'mid-scree-band', speed: 0.28, color: '#7f8b86', amplitude: 7, baseY: 90 },
  ],
  terrainRules: {
    worldWidth: 640,
    worldHeight: 144,
    sampleStep: 16,
    zones: [
      { id: 'thin-canopy', label: 'Thin Canopy', start: 0, end: 154, surfaceBaseY: 108, surfaceVariance: 4 },
      { id: 'krummholz-belt', label: 'Krummholz Belt', start: 154, end: 328, surfaceBaseY: 110, surfaceVariance: 5 },
      { id: 'dwarf-shrub', label: 'Dwarf Shrub', start: 328, end: 504, surfaceBaseY: 124, surfaceVariance: 3 },
      { id: 'lichen-fell', label: 'Lichen Fell', start: 504, end: 640, surfaceBaseY: 110, surfaceVariance: 6 },
    ],
    platformRules: [
      {
        id: 'wind-cut-ledge',
        zoneId: 'krummholz-belt',
        minCount: 1,
        maxCount: 2,
        minWidth: 18,
        maxWidth: 28,
        height: 4,
        liftMin: 8,
        liftMax: 13,
        spriteId: 'granite-platform',
      },
      {
        id: 'fell-stone-step',
        zoneId: 'lichen-fell',
        minCount: 1,
        maxCount: 2,
        minWidth: 18,
        maxWidth: 26,
        height: 4,
        liftMin: 8,
        liftMax: 12,
        spriteId: 'granite-platform',
      },
    ],
    authoredPlatforms: [
      {
        id: 'lee-pocket-entry-stone',
        spriteId: 'granite-platform',
        x: 258,
        y: 112,
        w: 24,
        h: 4,
      },
      {
        id: 'lee-pocket-upper-shelf',
        spriteId: 'granite-platform',
        x: 294,
        y: 110,
        w: 122,
        h: 4,
      },
      {
        id: 'lee-pocket-crest-step',
        spriteId: 'granite-platform',
        x: 422,
        y: 96,
        w: 22,
        h: 4,
      },
      {
        id: 'lee-pocket-rime-rest',
        spriteId: 'granite-platform',
        x: 452,
        y: 88,
        w: 32,
        h: 4,
      },
      {
        id: 'lee-pocket-back-notch',
        spriteId: 'granite-platform',
        x: 468,
        y: 110,
        w: 24,
        h: 4,
      },
      {
        id: 'lee-pocket-rime-cap',
        spriteId: 'granite-platform',
        x: 488,
        y: 88,
        w: 16,
        h: 4,
      },
      {
        id: 'lee-pocket-crest-brow',
        spriteId: 'granite-platform',
        x: 506,
        y: 80,
        w: 20,
        h: 4,
      },
      {
        id: 'lee-pocket-exit-stone',
        spriteId: 'granite-platform',
        x: 406,
        y: 112,
        w: 24,
        h: 4,
      },
      {
        id: 'lee-pocket-fell-return',
        spriteId: 'granite-platform',
        x: 516,
        y: 96,
        w: 22,
        h: 4,
      },
      {
        id: 'lee-pocket-lee-rest',
        spriteId: 'granite-platform',
        x: 538,
        y: 102,
        w: 20,
        h: 4,
      },
    ],
    authoredEntities: [
      {
        id: 'thin-canopy-bunchberry',
        entryId: 'bunchberry',
        x: 112,
        y: 100,
      },
      {
        id: 'krummholz-bunchberry',
        entryId: 'bunchberry',
        x: 210,
        y: 102,
      },
      {
        id: 'lee-pocket-rime-campion',
        entryId: 'moss-campion',
        x: 460,
        y: 84,
        castsShadow: false,
      },
      {
        id: 'lee-pocket-rime-talus',
        entryId: 'talus-cushion-pocket',
        x: 448,
        y: 90,
        castsShadow: false,
      },
      {
        id: 'fell-return-talus',
        entryId: 'talus-cushion-pocket',
        x: 500,
        y: 102,
        castsShadow: false,
      },
      {
        id: 'lee-pocket-crest-avens',
        entryId: 'mountain-avens',
        x: 514,
        y: 76,
        castsShadow: false,
      },
    ],
  },
  spawnTables: [
    {
      id: 'stable-thin-canopy',
      zoneId: 'thin-canopy',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 32,
      entries: [
        { entryId: 'mountain-hemlock', weight: 2 },
        { entryId: 'bunchberry', weight: 1 },
      ],
    },
    {
      id: 'stable-krummholz-belt',
      zoneId: 'krummholz-belt',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 24,
      entries: [
        { entryId: 'dwarf-birch', weight: 4 },
        { entryId: 'mountain-hemlock', weight: 1 },
        { entryId: 'bunchberry', weight: 1 },
      ],
    },
    {
      id: 'stable-krummholz-landmark',
      zoneId: 'krummholz-belt',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 12,
      entries: [{ entryId: 'krummholz-spruce', weight: 1 }],
    },
    {
      id: 'stable-dwarf-shrubs',
      zoneId: 'dwarf-shrub',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 22,
      entries: [
        { entryId: 'dwarf-birch', weight: 3 },
        { entryId: 'bog-blueberry', weight: 2 },
        { entryId: 'crowberry', weight: 2 },
      ],
    },
    {
      id: 'stable-heath-mats',
      zoneId: 'dwarf-shrub',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'white-arctic-mountain-heather', weight: 1 }],
    },
    {
      id: 'stable-shelter-boulder',
      zoneId: 'dwarf-shrub',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 12,
      entries: [{ entryId: 'frost-heave-boulder', weight: 1 }],
    },
    {
      id: 'stable-lichen-patches',
      zoneId: 'lichen-fell',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 22,
      entries: [{ entryId: 'reindeer-lichen', weight: 1 }],
    },
    {
      id: 'stable-fell-ground',
      zoneId: 'lichen-fell',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 22,
      entries: [
        { entryId: 'mountain-avens', weight: 3 },
        { entryId: 'moss-campion', weight: 2 },
        { entryId: 'arctic-willow', weight: 2 },
      ],
    },
    {
      id: 'stable-fell-heaths',
      zoneId: 'lichen-fell',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'white-arctic-mountain-heather', weight: 1 }],
    },
    {
      id: 'stable-fell-boulder',
      zoneId: 'lichen-fell',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 1,
      spacing: 12,
      entries: [{ entryId: 'frost-heave-boulder', weight: 1 }],
    },
    {
      id: 'berry-patches',
      zoneId: 'dwarf-shrub',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 18,
      entries: [
        { entryId: 'bog-blueberry', weight: 3 },
        { entryId: 'crowberry', weight: 2 },
        { entryId: 'lingonberry', weight: 2 },
      ],
    },
    {
      id: 'fell-berries',
      zoneId: 'lichen-fell',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 22,
      entries: [
        { entryId: 'crowberry', weight: 2 },
        { entryId: 'lingonberry', weight: 1 },
      ],
    },
    {
      id: 'krummholz-life',
      zoneId: 'krummholz-belt',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 32,
      entries: [
        { entryId: 'ermine', weight: 3 },
        { entryId: 'rock-ptarmigan', weight: 1 },
      ],
    },
    {
      id: 'open-fell-life',
      zoneId: 'lichen-fell',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [
        { entryId: 'rock-ptarmigan', weight: 3 },
        { entryId: 'ermine', weight: 1 },
      ],
    },
    {
      id: 'talus-life',
      zoneId: 'lichen-fell',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 36,
      entries: [{ entryId: 'hoary-marmot', weight: 1 }],
    },
    {
      id: 'lee-pocket-life',
      zoneId: 'dwarf-shrub',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 34,
      entries: [
        { entryId: 'hoary-marmot', weight: 3 },
        { entryId: 'rock-ptarmigan', weight: 1 },
      ],
    },
  ],
  ambientRules: {
    cloudCount: [1, 2],
    sparkleCount: [8, 14],
  },
  entries: treelineEntries,
  ecosystemNotes: [
    {
      id: 'tree-line-drops',
      title: 'Tree Line Drops',
      entryIds: ['mountain-avens', 'krummholz-spruce', 'dwarf-birch'],
      minimumDiscoveries: 3,
      summary:
        'As tree shapes shrink and blooms hug the ground, treeline gives way to open fell.',
      observationPrompt:
        'Where does tree cover drop into low fell here?',
      zoneId: 'lichen-fell',
    },
    {
      id: 'wind-shapes-trees',
      title: 'Wind Shapes Trees',
      entryIds: ['mountain-hemlock', 'krummholz-spruce', 'dwarf-birch'],
      summary:
        'As wind and cold rise, tall trees give way to low woody growth.',
      observationPrompt:
        'Which plants still look tree-shaped here?',
      zoneId: 'krummholz-belt',
    },
    {
      id: 'fell-bloom-window',
      title: 'Fell Bloom Window',
      entryIds: ['mountain-avens', 'moss-campion'],
      summary:
        'On exposed fell, low mat flowers bloom fast in the small calm layer just above the ground.',
      observationPrompt:
        'Which bloom hugs the calmest ground here?',
      zoneId: 'lichen-fell',
    },
    {
      id: 'heath-berry-mats',
      title: 'Heath Berry Mats',
      entryIds: ['white-arctic-mountain-heather', 'lingonberry', 'bog-blueberry'],
      minimumDiscoveries: 2,
      summary:
        'Low heaths and berry shrubs share calmer patches just below the open fell.',
      observationPrompt:
        'Which patch here feels calm enough for berry mats?',
      zoneId: 'dwarf-shrub',
    },
    {
      id: 'low-ground-wins',
      title: 'Low Ground Wins',
      entryIds: ['moss-campion', 'arctic-willow', 'reindeer-lichen', 'crowberry'],
      summary:
        'Near the fell, low shrubs and lichens handle wind better than tall plants.',
      observationPrompt:
        'What stays closest to the ground here?',
      zoneId: 'lichen-fell',
    },
    {
      id: 'stone-shelter',
      title: 'Stone Shelter',
      entryIds: ['frost-heave-boulder', 'hoary-marmot', 'krummholz-spruce'],
      minimumDiscoveries: 2,
      summary:
        'Near treeline, bent wood and raised stone make calmer pockets that animals can also use.',
      observationPrompt:
        'What here breaks the wind first?',
      zoneId: 'dwarf-shrub',
    },
    {
      id: 'cold-ground-works',
      title: 'Cold Ground Works',
      entryIds: ['dwarf-birch', 'reindeer-lichen', 'frost-heave-boulder'],
      minimumDiscoveries: 2,
      summary:
        'Freeze-thaw stone and low growth show where cold ground still shapes the fell.',
      observationPrompt:
        'What here still looks shaped by cold ground?',
    },
    {
      id: 'talus-islands',
      title: 'Talus Islands',
      entryIds: ['talus-cushion-pocket', 'moss-campion', 'frost-heave-boulder'],
      minimumDiscoveries: 2,
      summary:
        'Among bare alpine stones, tiny sheltered pockets let low life keep a foothold.',
      observationPrompt:
        'What here stays alive between bare stones?',
      zoneId: 'lichen-fell',
    },
    {
      id: 'broken-canopy-floor',
      title: 'Broken Canopy Floor',
      entryIds: ['bunchberry', 'mountain-hemlock', 'dwarf-birch'],
      minimumDiscoveries: 2,
      summary:
        'Low floor plants still hold on under the last mountain trees, but shrubs and brighter wind reach the ground.',
      observationPrompt:
        'What still feels like forest floor here?',
      zoneId: 'krummholz-belt',
    },
  ],
  verticalCues: [
    {
      id: 'lee-pocket-rime-light',
      style: 'canopy-opening',
      x: 458,
      y: 80,
      zoneIds: ['dwarf-shrub', 'lichen-fell'],
    },
  ],
  phenology: {
    phases: {
      early: {
        skyWashTop: 'rgba(239, 242, 248, 0.12)',
        skyWashBottom: 'rgba(244, 247, 250, 0.06)',
        groundWash: 'rgba(213, 221, 229, 0.10)',
        parallaxColors: ['#d7dde0', '#96a19d'],
        entryAccents: [
          { entryId: 'mountain-avens', style: 'frost', primaryColor: '#f7fbff', secondaryColor: '#d8e4ef' },
          { entryId: 'moss-campion', style: 'frost', primaryColor: '#f6fbff', secondaryColor: '#d7e0ea' },
        ],
      },
      peak: {
        skyWashTop: 'rgba(232, 234, 228, 0.06)',
        skyWashBottom: 'rgba(243, 241, 235, 0.05)',
        groundWash: 'rgba(166, 176, 144, 0.10)',
        parallaxColors: ['#d4d5cb', '#8f9894'],
        entryAccents: [
          { entryId: 'mountain-avens', style: 'bloom', primaryColor: '#fff5d5', secondaryColor: '#e0c56d' },
          { entryId: 'moss-campion', style: 'bloom', primaryColor: '#d86e9d', secondaryColor: '#f3bdd2' },
        ],
      },
      late: {
        skyWashTop: 'rgba(222, 215, 206, 0.08)',
        skyWashBottom: 'rgba(231, 227, 218, 0.05)',
        groundWash: 'rgba(150, 137, 111, 0.11)',
        parallaxColors: ['#cbc5ba', '#7b817d'],
        entryAccents: [
          { entryId: 'bog-blueberry', style: 'berry', primaryColor: '#4a5fb2', secondaryColor: '#bbc8f6' },
          { entryId: 'crowberry', style: 'berry', primaryColor: '#322c4d', secondaryColor: '#8f88bd' },
        ],
        spawnEmphasis: [{ tableId: 'berry-patches', minCountDelta: 1, maxCountDelta: 1 }],
      },
    },
  },
  processMoments: [
    {
      id: 'frost-rime',
      style: 'frost-rime',
      entryIds: ['dwarf-birch', 'reindeer-lichen', 'frost-heave-boulder'],
      zoneIds: ['dwarf-shrub', 'lichen-fell'],
      minimumVisitCount: 2,
      weatherProfiles: ['ridge-wind'],
      phenologyPhases: ['late'],
      primaryColor: '#edf4fb',
      secondaryColor: '#bdcad8',
    },
  ],
  startPosition: {
    x: 24,
    y: 82,
  },
};
