import { tundraPalette } from '../../assets/palette';
import type { BiomeDefinition } from '../../engine/types';
import {
  arcticWillowEntry,
  crowberryEntry,
  lingonberryEntry,
  mossCampionEntry,
  mountainAvensEntry,
  reindeerLichenEntry,
} from '../shared-entries';

const tundraEntries = {
  'arctic-willow': arcticWillowEntry,
  'mountain-avens': mountainAvensEntry,
  'moss-campion': mossCampionEntry,
  'reindeer-lichen': reindeerLichenEntry,
  'purple-saxifrage': {
    id: 'purple-saxifrage',
    commonName: 'Purple Saxifrage',
    scientificName: 'Saxifraga oppositifolia',
    category: 'plant',
    shortFact: 'Purple saxifrage can bloom soon after snow starts to melt.',
    journalText:
      'Purple saxifrage is one of the first flowers to brighten Arctic ground. Its low mats help protect the plant from cold air and drying wind.',
    spriteId: 'purple-saxifrage',
    collectible: false,
  },
  cottongrass: {
    id: 'cottongrass',
    commonName: 'Cottongrass',
    scientificName: 'Eriophorum angustifolium',
    category: 'plant',
    shortFact: 'Its fluffy seed heads help wind carry new seeds across wet tundra.',
    journalText:
      'Cottongrass grows in soggy Arctic soil. The white tufts are not cotton at all. They are seed fibers that help spread the plant.',
    sketchbookNote: 'White tufts marking a brief wet thaw band.',
    spriteId: 'cottongrass',
    collectible: false,
  },
  'woolly-lousewort': {
    id: 'woolly-lousewort',
    commonName: 'Woolly Lousewort',
    scientificName: 'Pedicularis dasyantha',
    category: 'plant',
    shortFact: 'Woolly lousewort keeps fuzzy stems that help with cold, windy tundra weather.',
    journalText:
      'Woolly lousewort grows on open tundra where wind and cold can be harsh. Its fuzzy stem helps trap a little warmer air close to the plant.',
    spriteId: 'woolly-lousewort',
    collectible: false,
  },
  cloudberry: {
    id: 'cloudberry',
    commonName: 'Cloudberry',
    scientificName: 'Rubus chamaemorus',
    category: 'plant',
    shortFact: 'Cloudberries ripen quickly during the short Arctic summer.',
    journalText:
      'Cloudberry plants stay small and low, but their orange berries are full of energy. Birds, bears, and people all eat them when summer is at its brightest.',
    spriteId: 'cloudberry',
    collectible: true,
  },
  lingonberry: lingonberryEntry,
  crowberry: crowberryEntry,
  'bigelows-sedge': {
    id: 'bigelows-sedge',
    commonName: "Bigelow's Sedge",
    scientificName: 'Carex bigelowii',
    category: 'plant',
    shortFact: "Bigelow's sedge grows in low tussocks that lift leaves above wet, cold tundra soil.",
    journalText:
      "Bigelow's sedge is a low northern sedge that often grows in raised tussocks. Those springy clumps help shape wet tundra ground and can give small animals cover between stems.",
    sketchbookNote: 'Raised tussocks shaping wet tundra ground.',
    spriteId: 'bigelows-sedge',
    collectible: false,
  },
  'tussock-thaw-channel': {
    id: 'tussock-thaw-channel',
    commonName: 'Tussock Thaw Channel',
    category: 'landmark',
    subtitle: 'Wet space between tussocks',
    subtitleLabel: 'Habitat role',
    shortFact: 'Wet channels between tundra tussocks can hold tiny mossy ground through thaw.',
    journalText:
      'A tussock thaw channel is a low wet space between raised tundra clumps. Meltwater lingers there long enough for mossy ground and low plants to keep growing.',
    sketchbookNote: 'Wet low lane lingering between raised tundra tussocks.',
    spriteId: 'tussock-thaw-channel',
    collectible: false,
  },
  'arctic-hare': {
    id: 'arctic-hare',
    commonName: 'Arctic Hare',
    scientificName: 'Lepus arcticus',
    category: 'animal',
    shortFact: 'Wide feet help an Arctic hare run across snow and soft ground.',
    journalText:
      'Arctic hares have thick fur and powerful legs for cold places. Their pale coats help them blend into snowy ground during much of the year.',
    spriteId: 'arctic-hare',
    collectible: false,
  },
  'snow-bunting': {
    id: 'snow-bunting',
    commonName: 'Snow Bunting',
    scientificName: 'Plectrophenax nivalis',
    category: 'animal',
    shortFact: 'Snow buntings nest on the ground in rocky places where wind cannot reach as easily.',
    journalText:
      'Snow buntings are hardy birds that return north early in the season. They search the tundra for seeds and insects during the brief summer.',
    spriteId: 'snow-bunting',
    collectible: false,
  },
  'white-tailed-ptarmigan': {
    id: 'white-tailed-ptarmigan',
    commonName: 'White-tailed Ptarmigan',
    scientificName: 'Lagopus leucura',
    category: 'animal',
    shortFact: 'White-tailed ptarmigans stay near snowy alpine ground where rock and low plants give cover.',
    journalText:
      'White-tailed ptarmigans live high above treeline near snow patches, rocks, and low alpine plants. Their feathered feet help them move across cold ground in every season.',
    spriteId: 'white-tailed-ptarmigan',
    collectible: true,
  },
  'northern-collared-lemming': {
    id: 'northern-collared-lemming',
    commonName: 'Northern Collared Lemming',
    scientificName: 'Dicrostonyx groenlandicus',
    category: 'animal',
    shortFact: 'Northern collared lemmings live low in tundra plants where snow can cover them.',
    journalText:
      'Northern collared lemmings are small tundra rodents that move through low plants and snowy cover. They are an important food source for many Arctic predators.',
    spriteId: 'northern-collared-lemming',
    collectible: false,
  },
  'frost-heave-hummock': {
    id: 'frost-heave-hummock',
    commonName: 'Frost-Heave Hummock',
    category: 'landmark',
    subtitle: 'Freeze-thaw mound',
    subtitleLabel: 'Ground clue',
    shortFact: 'Freeze-thaw ground can push tundra soil into small hummocks.',
    journalText:
      'A frost-heave hummock is a small tundra mound shaped by ground that freezes, lifts, and settles again. Cold soil can slowly reshape the land without anyone digging it.',
    sketchbookNote: 'Raised hummock showing freeze-thaw at work.',
    spriteId: 'frost-heave-hummock',
    collectible: false,
  },
} satisfies BiomeDefinition['entries'];

export const tundraBiome: BiomeDefinition = {
  id: 'tundra',
  name: 'Tundra Reach',
  palette: tundraPalette,
  tileSet: ['snow-top', 'permafrost-fill', 'ice-platform'],
  parallaxLayers: [
    { id: 'far-ice', speed: 0.12, color: '#d7e9f4', amplitude: 4, baseY: 70 },
    { id: 'frost-ridge', speed: 0.28, color: '#9db9cb', amplitude: 7, baseY: 88 },
  ],
  terrainRules: {
    worldWidth: 640,
    worldHeight: 144,
    sampleStep: 16,
    zones: [
      { id: 'wind-bluff', label: 'Wind Bluff', start: 0, end: 150, surfaceBaseY: 108, surfaceVariance: 4 },
      { id: 'snow-meadow', label: 'Snow Meadow', start: 150, end: 304, surfaceBaseY: 112, surfaceVariance: 3 },
      { id: 'thaw-skirt', label: 'Thaw Skirt', start: 304, end: 408, surfaceBaseY: 118, surfaceVariance: 4 },
      { id: 'frost-ridge', label: 'Frost Ridge', start: 408, end: 520, surfaceBaseY: 109, surfaceVariance: 5 },
      { id: 'meltwater-edge', label: 'Meltwater Edge', start: 520, end: 640, surfaceBaseY: 114, surfaceVariance: 4 },
    ],
    platformRules: [
      {
        id: 'ice-shelf',
        zoneId: 'snow-meadow',
        minCount: 1,
        maxCount: 2,
        minWidth: 18,
        maxWidth: 28,
        height: 4,
        liftMin: 8,
        liftMax: 12,
        spriteId: 'ice-platform',
      },
      {
        id: 'ridge-ledge',
        zoneId: 'frost-ridge',
        minCount: 1,
        maxCount: 2,
        minWidth: 16,
        maxWidth: 24,
        height: 4,
        liftMin: 9,
        liftMax: 14,
        spriteId: 'ice-platform',
      },
    ],
    authoredPlatforms: [
      {
        id: 'wind-bluff-heave-shoulder',
        spriteId: 'ice-platform',
        x: 128,
        y: 108,
        w: 16,
        h: 4,
      },
      {
        id: 'snow-threshold-lee-rest',
        spriteId: 'ice-platform',
        x: 150,
        y: 111,
        w: 28,
        h: 4,
      },
      {
        id: 'thaw-skirt-entry-heave',
        spriteId: 'ice-platform',
        x: 314,
        y: 104,
        w: 24,
        h: 4,
      },
      {
        id: 'thaw-skirt-upper-shelf',
        spriteId: 'ice-platform',
        x: 348,
        y: 98,
        w: 72,
        h: 4,
      },
      {
        id: 'thaw-skirt-bank-shoulder',
        spriteId: 'ice-platform',
        x: 420,
        y: 104,
        w: 20,
        h: 4,
      },
      {
        id: 'thaw-skirt-exit-heave',
        spriteId: 'ice-platform',
        x: 444,
        y: 103,
        w: 24,
        h: 4,
      },
      {
        id: 'frost-ridge-drift-rest',
        spriteId: 'ice-platform',
        x: 500,
        y: 102,
        w: 22,
        h: 4,
      },
      {
        id: 'meltwater-snow-lip',
        spriteId: 'ice-platform',
        x: 538,
        y: 109,
        w: 22,
        h: 4,
      },
      {
        id: 'meltwater-bank-rest',
        spriteId: 'ice-platform',
        x: 574,
        y: 112,
        w: 26,
        h: 4,
      },
    ],
    authoredEntities: [
      {
        id: 'wind-bluff-hummock',
        entryId: 'frost-heave-hummock',
        x: 82,
        y: 102,
      },
      {
        id: 'wind-bluff-lichen',
        entryId: 'reindeer-lichen',
        x: 110,
        y: 101,
      },
      {
        id: 'wind-bluff-campion',
        entryId: 'moss-campion',
        x: 136,
        y: 102,
      },
      {
        id: 'snow-threshold-hummock',
        entryId: 'frost-heave-hummock',
        x: 156,
        y: 105,
      },
      {
        id: 'snow-threshold-lichen',
        entryId: 'reindeer-lichen',
        x: 172,
        y: 105,
      },
      {
        id: 'thaw-skirt-channel',
        entryId: 'tussock-thaw-channel',
        x: 362,
        y: 104,
        castsShadow: false,
      },
      {
        id: 'meltwater-channel',
        entryId: 'tussock-thaw-channel',
        x: 544,
        y: 112,
        castsShadow: false,
      },
      {
        id: 'meltwater-bank-willow',
        entryId: 'arctic-willow',
        x: 582,
        y: 109,
      },
      {
        id: 'meltwater-bank-cottongrass',
        entryId: 'cottongrass',
        x: 592,
        y: 109,
      },
      {
        id: 'frost-ridge-hummock',
        entryId: 'frost-heave-hummock',
        x: 468,
        y: 100,
      },
      {
        id: 'frost-ridge-campion',
        entryId: 'moss-campion',
        x: 492,
        y: 100,
      },
    ],
  },
  spawnTables: [
    {
      id: 'stable-willow',
      zoneId: 'wind-bluff',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 30,
      entries: [{ entryId: 'arctic-willow', weight: 1 }],
    },
    {
      id: 'stable-wind-lichen',
      zoneId: 'wind-bluff',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'reindeer-lichen', weight: 1 }],
    },
    {
      id: 'stable-wind-cushions',
      zoneId: 'wind-bluff',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'moss-campion', weight: 1 }],
    },
    {
      id: 'stable-flowers',
      zoneId: 'snow-meadow',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 22,
      entries: [{ entryId: 'purple-saxifrage', weight: 4 }],
    },
    {
      id: 'stable-sedge-tussocks',
      zoneId: 'snow-meadow',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'bigelows-sedge', weight: 1 }],
    },
    {
      id: 'stable-grasses',
      zoneId: 'meltwater-edge',
      refreshPolicy: 'stable',
      minCount: 2,
      maxCount: 3,
      spacing: 26,
      entries: [
        { entryId: 'cottongrass', weight: 4 },
        { entryId: 'arctic-willow', weight: 2 },
      ],
    },
    {
      id: 'stable-ridge-flowers',
      zoneId: 'frost-ridge',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'woolly-lousewort', weight: 1 }],
    },
    {
      id: 'stable-ridge-mats',
      zoneId: 'frost-ridge',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 26,
      entries: [
        { entryId: 'mountain-avens', weight: 3 },
        { entryId: 'moss-campion', weight: 2 },
      ],
    },
    {
      id: 'stable-ridge-lichen',
      zoneId: 'frost-ridge',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'reindeer-lichen', weight: 1 }],
    },
    {
      id: 'stable-thaw-edge',
      zoneId: 'thaw-skirt',
      refreshPolicy: 'stable',
      minCount: 3,
      maxCount: 4,
      spacing: 22,
      entries: [
        { entryId: 'purple-saxifrage', weight: 2 },
        { entryId: 'cottongrass', weight: 2 },
        { entryId: 'arctic-willow', weight: 1 },
      ],
    },
    {
      id: 'stable-thaw-tussocks',
      zoneId: 'thaw-skirt',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'bigelows-sedge', weight: 1 }],
    },
    {
      id: 'stable-thaw-shelter',
      zoneId: 'thaw-skirt',
      refreshPolicy: 'stable',
      minCount: 1,
      maxCount: 2,
      spacing: 24,
      entries: [{ entryId: 'woolly-lousewort', weight: 1 }],
    },
    {
      id: 'berry-patches',
      zoneId: 'snow-meadow',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 20,
      entries: [
        { entryId: 'cloudberry', weight: 3 },
        { entryId: 'crowberry', weight: 2 },
        { entryId: 'lingonberry', weight: 2 },
      ],
    },
    {
      id: 'snow-edge-birds',
      zoneId: 'snow-meadow',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 1,
      spacing: 34,
      entries: [{ entryId: 'white-tailed-ptarmigan', weight: 1 }],
    },
    {
      id: 'ridge-berries',
      zoneId: 'frost-ridge',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 18,
      entries: [
        { entryId: 'crowberry', weight: 3 },
        { entryId: 'cloudberry', weight: 1 },
        { entryId: 'lingonberry', weight: 1 },
      ],
    },
    {
      id: 'tundra-life',
      zoneId: 'wind-bluff',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 34,
      entries: [
        { entryId: 'arctic-hare', weight: 3 },
        { entryId: 'snow-bunting', weight: 2 },
      ],
    },
    {
      id: 'meltwater-life',
      zoneId: 'meltwater-edge',
      refreshPolicy: 'visit',
      minCount: 2,
      maxCount: 3,
      spacing: 28,
      entries: [
        { entryId: 'snow-bunting', weight: 3 },
        { entryId: 'arctic-hare', weight: 1 },
      ],
    },
    {
      id: 'tussock-life',
      zoneId: 'snow-meadow',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 30,
      entries: [{ entryId: 'northern-collared-lemming', weight: 1 }],
    },
    {
      id: 'thaw-skirt-life',
      zoneId: 'thaw-skirt',
      refreshPolicy: 'visit',
      minCount: 1,
      maxCount: 2,
      spacing: 28,
      entries: [
        { entryId: 'northern-collared-lemming', weight: 2 },
        { entryId: 'snow-bunting', weight: 1 },
        { entryId: 'white-tailed-ptarmigan', weight: 1 },
      ],
    },
  ],
  ambientRules: {
    cloudCount: [1, 3],
    sparkleCount: [10, 16],
  },
  entries: tundraEntries,
  ecosystemNotes: [
    {
      id: 'staying-low',
      title: 'Staying Low',
      entryIds: ['arctic-willow', 'purple-saxifrage', 'woolly-lousewort', 'crowberry'],
      summary:
        'Low tundra plants stay near calmer, slightly warmer air.',
      observationPrompt:
        'Which shapes hide from strong wind?',
      zoneId: 'wind-bluff',
    },
    {
      id: 'tussock-ground',
      title: 'Tussock Ground',
      entryIds: ['bigelows-sedge', 'cottongrass', 'northern-collared-lemming'],
      minimumDiscoveries: 2,
      summary:
        'Raised sedge tussocks make springy ground that protects wet soil and gives small animals cover.',
      observationPrompt:
        'What here makes the ground feel springier?',
      zoneId: 'snow-meadow',
    },
    {
      id: 'brief-thaw-bloom',
      title: 'Brief Thaw Bloom',
      entryIds: ['mountain-avens', 'woolly-lousewort'],
      summary:
        'On exposed tundra ridges, low flowers use brief thaws before the cold wind returns.',
      observationPrompt:
        'Which bloom seems built for a brief thaw?',
      zoneId: 'frost-ridge',
    },
    {
      id: 'short-summer-rush',
      title: 'Short Summer Rush',
      entryIds: ['purple-saxifrage', 'cloudberry', 'snow-bunting'],
      summary:
        'Plants and birds must use the short summer fast.',
      observationPrompt:
        'What hints at a very short summer?',
      zoneId: 'snow-meadow',
    },
    {
      id: 'thaw-edge',
      title: 'Thaw Edge',
      entryIds: ['arctic-willow', 'purple-saxifrage', 'cottongrass'],
      minimumDiscoveries: 2,
      summary:
        'Low shrubs, blooms, and tufts mark the brief wet edge where tundra starts to thaw.',
      observationPrompt:
        'What here marks the wet edge of thaw?',
      zoneId: 'thaw-skirt',
    },
    {
      id: 'evergreen-berry-mats',
      title: 'Evergreen Berry Mats',
      entryIds: ['lingonberry', 'crowberry'],
      minimumDiscoveries: 2,
      summary:
        'Low evergreen berry mats hug open tundra where wind passes over them.',
      observationPrompt:
        'Which berries stay low through cold wind?',
      zoneId: 'frost-ridge',
    },
    {
      id: 'wind-cut-cushions',
      title: 'Wind-Cut Cushions',
      entryIds: ['moss-campion', 'reindeer-lichen', 'frost-heave-hummock'],
      minimumDiscoveries: 2,
      summary:
        'Tiny cushion flowers and pale lichens stay low where cold wind skims across the bluff.',
      observationPrompt:
        'What here stays alive on the most exposed ground?',
      zoneId: 'wind-bluff',
    },
    {
      id: 'between-tussocks',
      title: 'Between Tussocks',
      entryIds: ['tussock-thaw-channel', 'bigelows-sedge', 'cottongrass'],
      minimumDiscoveries: 2,
      summary:
        'Between raised tundra tussocks, wetter low channels hold thaw water and tiny ground cover.',
      observationPrompt:
        'What here grows in the low wet spaces?',
      zoneId: 'thaw-skirt',
    },
  ],
  phenology: {
    phases: {
      early: {
        skyWashTop: 'rgba(246, 248, 252, 0.14)',
        skyWashBottom: 'rgba(238, 243, 248, 0.08)',
        groundWash: 'rgba(226, 236, 243, 0.11)',
        parallaxColors: ['#e2edf3', '#a7bfd0'],
        entryAccents: [
          { entryId: 'purple-saxifrage', style: 'bloom', primaryColor: '#b183df', secondaryColor: '#e2c8f9' },
        ],
      },
      peak: {
        skyWashTop: 'rgba(231, 241, 236, 0.08)',
        skyWashBottom: 'rgba(235, 243, 241, 0.05)',
        groundWash: 'rgba(169, 201, 175, 0.08)',
        parallaxColors: ['#d7e8ea', '#97b3be'],
        entryAccents: [
          { entryId: 'mountain-avens', style: 'bloom', primaryColor: '#fff3cf', secondaryColor: '#dcc36f' },
          { entryId: 'cloudberry', style: 'berry', primaryColor: '#efab52', secondaryColor: '#ffdeb5' },
          { entryId: 'moss-campion', style: 'bloom', primaryColor: '#d86e9d', secondaryColor: '#f3bdd2' },
          { entryId: 'woolly-lousewort', style: 'bloom', primaryColor: '#cb84b0', secondaryColor: '#f0c6df' },
        ],
        spawnEmphasis: [{ tableId: 'berry-patches', minCountDelta: 1, maxCountDelta: 1 }],
      },
      late: {
        skyWashTop: 'rgba(227, 227, 236, 0.10)',
        skyWashBottom: 'rgba(233, 237, 243, 0.06)',
        groundWash: 'rgba(190, 196, 180, 0.10)',
        parallaxColors: ['#d6e0e8', '#91a9b8'],
        entryAccents: [
          { entryId: 'cottongrass', style: 'tuft', primaryColor: '#f8fbff', secondaryColor: '#d5dfec' },
          { entryId: 'crowberry', style: 'berry', primaryColor: '#2f2d49', secondaryColor: '#8f8db8' },
        ],
        spawnEmphasis: [{ tableId: 'ridge-berries', minCountDelta: 1, maxCountDelta: 1 }],
      },
    },
  },
  processMoments: [
    {
      id: 'thaw-fringe',
      style: 'thaw-fringe',
      entryIds: ['arctic-willow', 'purple-saxifrage', 'cottongrass'],
      zoneIds: ['snow-meadow', 'thaw-skirt', 'meltwater-edge'],
      minimumVisitCount: 2,
      phenologyPhases: ['peak'],
      primaryColor: '#76a7a3',
      secondaryColor: '#e6f4ec',
    },
  ],
  startPosition: {
    x: 24,
    y: 82,
  },
};
