import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const coastalFloraSprites: SpriteSource[] = [
  {
    id: 'dune-lupine',
    palette: {
      a: masterPalette.scrubSageDark,
      b: masterPalette.scrubSageLight,
      c: '#8f73d0',
      d: '#d4c0f5',
    },
    frames: [[
      '....c...',
      '...cdc..',
      '..bbd...',
      '...ba...',
      '..bbba..',
      '.babb...',
      '..abb...',
      '.abbb...',
      '..aaa...',
      '.aaaba..',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'pacific-wax-myrtle',
    palette: {
      a: masterPalette.scrubSageDark,
      b: masterPalette.scrubSageLight,
      c: masterPalette.bayberryBlue,
      d: '#b7c0d3',
      e: '#806048',
    },
    frames: [[
      '...cc...',
      '..cddc..',
      '.bcddcb.',
      '..abba..',
      '.abbba..',
      '.bbabb..',
      '..abbb..',
      '.abbba..',
      '...e....',
      '..eee...',
      '.eeeee..',
      '........',
    ]],
  },
  {
    id: 'shore-pine',
    palette: {
      a: masterPalette.shorePine,
      b: masterPalette.scrubSageLight,
      c: '#7b5b41',
    },
    frames: [[
      '....a...',
      '...aba..',
      '..ababa.',
      '...aba..',
      '..abbba.',
      '.abbbbba',
      '...aca..',
      '..accca.',
      '..accca.',
      '.accccca',
      '...c.c..',
      '........',
    ]],
  },
  {
    id: 'coyote-brush',
    palette: {
      a: masterPalette.scrubSageDark,
      b: masterPalette.scrubOlive,
      c: '#8a6b4b',
    },
    frames: [[
      '...aa...',
      '..abba..',
      '.abbbba.',
      '..abba..',
      '.abb b..',
      '.bbabb..',
      '..abbb..',
      '.abbba..',
      '...c....',
      '..ccc...',
      '.ccccc..',
      '........',
    ].map((row) => row.replace(/ /g, '.'))],
  },
  {
    id: 'nootka-rose',
    palette: {
      a: masterPalette.scrubSageDark,
      b: masterPalette.scrubSageLight,
      c: masterPalette.shellPink,
      d: masterPalette.coral,
      e: '#7d5a42',
    },
    frames: [[
      '...cc...',
      '..cddc..',
      '.abddba.',
      '..abba..',
      '.abbba..',
      '.bbabb..',
      '..abbb..',
      '.abbba..',
      '...e....',
      '..eee...',
      '.eeeee..',
      '........',
    ]],
  },
];
