import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const floraSprites: SpriteSource[] = [
  {
    id: 'beach-grass',
    palette: {
      a: masterPalette.leafDark,
      b: masterPalette.leafLight,
      c: masterPalette.stem,
    },
    frames: [[
      '....a...',
      '...ab...',
      '..abb...',
      '..abc...',
      '.abcbc..',
      '.abbcb..',
      '..cbc...',
      '...c....',
      '...c....',
      '..ccc...',
      '.ccccc..',
      '........',
    ]],
  },
  {
    id: 'beach-grass-early',
    palette: {
      a: '#5f8441',
      b: '#92b761',
      c: '#d1df8e',
    },
    frames: [[
      '....a...',
      '...ab...',
      '..abb...',
      '..abb...',
      '.abbbc..',
      '.abbcb..',
      '..bcb...',
      '...b....',
      '..bbb...',
      '.bbbbb..',
      '..bbb...',
      '........',
    ]],
  },
  {
    id: 'beach-grass-peak',
    palette: {
      a: '#5b7e3b',
      b: '#8faf55',
      c: '#d9e48b',
    },
    frames: [[
      '....a...',
      '...ab...',
      '..abb...',
      '..abc...',
      '.abcbc..',
      '.abbcb..',
      '..cbcb..',
      '..bcb...',
      '..bbb...',
      '.bbbbb..',
      '.cbbbc..',
      '........',
    ]],
  },
  {
    id: 'beach-grass-late',
    palette: {
      a: '#7b7b45',
      b: '#baa35a',
      c: '#efe0a3',
    },
    frames: [[
      '...c.c..',
      '....b...',
      '..abb...',
      '..abb...',
      '.abbbb..',
      '.abbba..',
      '..bbb...',
      '...b....',
      '..bbb...',
      '.bbbbb..',
      '.bbbbb..',
      '........',
    ]],
  },
  {
    id: 'sea-rocket',
    palette: {
      a: masterPalette.stem,
      b: masterPalette.leafLight,
      c: masterPalette.shellPink,
      d: masterPalette.shellCream,
    },
    frames: [[
      '....c...',
      '...cdc..',
      '..bbd...',
      '...ba...',
      '..bbba..',
      '.babb...',
      '...a....',
      '..bab...',
      '..aaa...',
      '.aaaaa..',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'pickleweed',
    palette: {
      a: masterPalette.leafDark,
      b: masterPalette.leafLight,
      c: masterPalette.stem,
    },
    frames: [[
      '..ab....',
      '..bb....',
      '.abb.a..',
      '.bbb.bb.',
      '..cb.bc.',
      '.cbbbc..',
      '.cbbbc..',
      '..ccc...',
      '..ccc...',
      '.ccccc..',
      '........',
      '........',
    ]],
  },
  {
    id: 'sand-verbena',
    palette: {
      a: masterPalette.stem,
      b: masterPalette.leafLight,
      c: masterPalette.sun,
      d: masterPalette.shellCream,
    },
    frames: [[
      '....c...',
      '...cdc..',
      '..bbd...',
      '..bbb...',
      '.babb...',
      '.bbbba..',
      '...a....',
      '..bab...',
      '..aaa...',
      '.aaaaa..',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'sand-verbena-early',
    palette: {
      a: '#7a8f4b',
      b: '#aabd66',
      c: '#d9cd96',
    },
    frames: [[
      '........',
      '....b...',
      '...bbb..',
      '..bbab..',
      '.bbbab..',
      '..bbb...',
      '.babb...',
      '..aaa...',
      '.aaaaa..',
      '..aaa...',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'sand-verbena-peak',
    palette: {
      a: masterPalette.stem,
      b: masterPalette.leafLight,
      c: masterPalette.sun,
      d: masterPalette.shellCream,
    },
    frames: [[
      '...cc...',
      '..cdc...',
      '.cbbdc..',
      '..bbb...',
      '.babbc..',
      '.bbbba..',
      '...a....',
      '..bab...',
      '..aaa...',
      '.aaaaa..',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'sand-verbena-late',
    palette: {
      a: '#92754c',
      b: '#c1a065',
      c: '#e8d7a1',
    },
    frames: [[
      '...c.c..',
      '....b...',
      '..abb...',
      '..bbb...',
      '.babbb..',
      '.bbbba..',
      '...a....',
      '..aba...',
      '..aaa...',
      '.aaaaa..',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'beach-pea',
    palette: {
      a: masterPalette.stem,
      b: masterPalette.leafLight,
      c: '#8f73d0',
      d: '#e5d9fb',
    },
    frames: [[
      '........',
      '...cc...',
      '..cddc..',
      '...ba...',
      '..bbba..',
      '.babb...',
      '..abba..',
      '.abbb...',
      '..aaa...',
      '.aaaaa..',
      '...a....',
      '........',
    ]],
  },
  {
    id: 'bunchberry',
    palette: {
      a: masterPalette.cloud,
      b: masterPalette.berryCoral,
      c: masterPalette.leafDark,
      d: masterPalette.leafLight,
      e: masterPalette.stem,
    },
    frames: [[
      '...a....',
      '..aba...',
      '.adcda..',
      '..ddd...',
      '.ddbdd..',
      '..ddd...',
      '.ccedc..',
      '..eeec..',
      '.eeeee..',
      '..eee...',
      '...e....',
      '........',
    ]],
  },
];
