import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const forestFloraSprites: SpriteSource[] = [
  {
    id: 'climb-trunk',
    palette: {
      a: masterPalette.barkDark,
      b: masterPalette.barkLight,
      c: masterPalette.soilDark,
    },
    frames: [[
      '..abba..',
      '..baab..',
      '..abba..',
      '..baab..',
      '..abba..',
      '..baab..',
      '..acca..',
      '..cccc..',
    ]],
  },
  {
    id: 'climb-canopy',
    palette: {
      a: masterPalette.canopyDark,
      b: masterPalette.canopyLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '.....aaab......',
      '...aabbbbaa....',
      '..abbbbbbbb....',
      '.abbbbabbbbba..',
      '.bbbbbbbbbbbba.',
      '.bbbbbbbbbbbba.',
      '..abbbbbbbbba..',
      '...abbbbbbba...',
      '....aacccaa....',
      '......ccc......',
      '.......c.......',
      '...............',
    ]],
  },
  {
    id: 'giant-canopy',
    palette: {
      a: masterPalette.canopyDark,
      b: masterPalette.canopyLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '............aaabbb..............',
      '.........aaabbbbbbaa............',
      '......aaabbbbbbbbbbbba..........',
      '....aabbbbbbbbbbbbbbbbba........',
      '...abbbbbbabbbbbbbbbbbbba.......',
      '..abbbbbbbbbbbbbbbbbbbbbba......',
      '..abbbbbbbbbbbbbbbbbbbbbba......',
      '...abbbbbbbbbbbbbbbbbbbba.......',
      '....aabbbbbbbbbbbbbbbbba........',
      '......aabbbbbbbbbbbbbaa.........',
      '.........aaabcccccbaa...........',
      '............ccccccc.............',
      '.............ccccc..............',
      '..............ccc...............',
      '...............c................',
      '................................',
    ]],
  },
  {
    id: 'douglas-fir-sapling',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '....a...',
      '...aba..',
      '...aba..',
      '..abbba.',
      '..abbba.',
      '.abbbbba',
      '...aca..',
      '..accca.',
      '..accca.',
      '.accccca',
      '...c.c..',
      '........',
    ]],
  },
  {
    id: 'licorice-fern',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.mossLight,
      d: masterPalette.barkLight,
    },
    frames: [[
      '...aa...',
      '..abca..',
      '.abbcca.',
      '..abb...',
      '.abbcca.',
      '..abb...',
      '...d....',
      '..ddd...',
      '.ddddd..',
      '........',
      '........',
      '........',
    ]],
  },
  {
    id: 'tree-lungwort',
    palette: {
      a: masterPalette.lichenPale,
      b: masterPalette.mist,
      c: masterPalette.mossDark,
      d: masterPalette.alpineStoneLight,
    },
    frames: [[
      '..aa....',
      '.abbaa..',
      '.abbba..',
      '..abba..',
      '.abbba..',
      '..abba..',
      '.accca..',
      '..cdc...',
      '.cdddc..',
      '..ddd...',
      '........',
      '........',
    ]],
  },
  {
    id: 'sword-fern',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '....a...',
      '...ab...',
      '..abb...',
      '.abbbb..',
      '..abb...',
      '.abbbb..',
      'abbbbba.',
      '..abb...',
      '.abbbb..',
      '..abb...',
      '...c....',
      '........',
    ]],
  },
  {
    id: 'redwood-sorrel',
    palette: {
      a: masterPalette.fernLight,
      b: masterPalette.mossDark,
      c: masterPalette.barkLight,
    },
    frames: [[
      '..aa....',
      '.abba...',
      '..aa....',
      '....aa..',
      '...abba.',
      '....aa..',
      '..aa....',
      '.abba...',
      '..aa.a..',
      '...bc...',
      '..ccc...',
      '........',
    ]],
  },
  {
    id: 'salal-berry',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.berryBlue,
      d: masterPalette.berryPink,
      e: masterPalette.barkLight,
    },
    frames: [[
      '...cc...',
      '..cddc..',
      '.bcddcb.',
      '..abba..',
      '.abb b..',
      '.bbabb..',
      '..abbb..',
      '.abbba..',
      '...e....',
      '..eee...',
      '.eeeee..',
      '........',
    ].map((row) => row.replace(/ /g, '.'))],
  },
  {
    id: 'western-trillium',
    palette: {
      a: masterPalette.cloud,
      b: masterPalette.seedTan,
      c: masterPalette.fernLight,
      d: masterPalette.barkLight,
    },
    frames: [[
      '...a....',
      '..aba...',
      '.aacaa..',
      '..aca...',
      '.caca...',
      '..ccc...',
      '.ccdc...',
      '..ddd...',
      '.ddddd..',
      '........',
      '........',
      '........',
    ]],
  },
];
