import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const forestFloraSprites: SpriteSource[] = [
  {
    id: 'douglas-fir-sapling',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '....a...',
      '...aba..',
      '...aba..',
      '..abbba.',
      '..abbba.',
      '.abbbbba',
      '...aca..',
      '..accca.',
      '..accca.',
      '.accccca',
      '...c.c..',
      '........',
    ]],
  },
  {
    id: 'sword-fern',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '....a...',
      '...ab...',
      '..abb...',
      '.abbbb..',
      '..abb...',
      '.abbbb..',
      'abbbbba.',
      '..abb...',
      '.abbbb..',
      '..abb...',
      '...c....',
      '........',
    ]],
  },
  {
    id: 'redwood-sorrel',
    palette: {
      a: masterPalette.fernLight,
      b: masterPalette.mossDark,
      c: masterPalette.barkLight,
    },
    frames: [[
      '..aa....',
      '.abba...',
      '..aa....',
      '....aa..',
      '...abba.',
      '....aa..',
      '..aa....',
      '.abba...',
      '..aa.a..',
      '...bc...',
      '..ccc...',
      '........',
    ]],
  },
  {
    id: 'salal-berry',
    palette: {
      a: masterPalette.fernDark,
      b: masterPalette.fernLight,
      c: masterPalette.berryBlue,
      d: masterPalette.berryPink,
      e: masterPalette.barkLight,
    },
    frames: [[
      '...cc...',
      '..cddc..',
      '.bcddcb.',
      '..abba..',
      '.abb b..',
      '.bbabb..',
      '..abbb..',
      '.abbba..',
      '...e....',
      '..eee...',
      '.eeeee..',
      '........',
    ].map((row) => row.replace(/ /g, '.'))],
  },
];
