import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const playerSprites: SpriteSource[] = [
  {
    id: 'player',
    palette: {
      a: masterPalette.hair,
      b: masterPalette.tealDark,
      c: masterPalette.teal,
      d: masterPalette.skin,
      e: masterPalette.shirt,
      f: masterPalette.pants,
      g: masterPalette.boot,
      h: masterPalette.ink,
    },
    frames: [
      [
        '...bb.....',
        '..bccb....',
        '..bddb....',
        '.bhddhb...',
        '.beeeeb...',
        '.beffeb...',
        '..effe....',
        '..f..f....',
        '.gf..fg...',
        '.g....g...',
        '..........',
        '..........',
      ],
      [
        '...bb.....',
        '..bccb....',
        '..bddb....',
        '.bhddhb...',
        '.beeeeb...',
        '.beffeb...',
        '..effe....',
        '..f..f....',
        '.g...fg...',
        '....g.....',
        '...g......',
        '..........',
      ],
      [
        '...bb.....',
        '..bccb....',
        '..bddb....',
        '.bhddhb...',
        '.beeeeb...',
        '.beffeb...',
        '..effe....',
        '..f..f....',
        '.gf...g...',
        '..g...g...',
        '..........',
        '..........',
      ],
      [
        '...bb.....',
        '..bccb....',
        '..bddb....',
        '.bhddhb...',
        '.beeeeb...',
        '.beffeb...',
        '..effe....',
        '..f..f....',
        '.gf...g...',
        '..g.g.....',
        '.g........',
        '..........',
      ],
    ],
  },
];
