import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const tileSprites: SpriteSource[] = [
  {
    id: 'sand-top',
    palette: {
      a: masterPalette.sandLight,
      b: masterPalette.sandMid,
      c: masterPalette.shellCream,
      d: masterPalette.sandDark,
    },
    frames: [[
      'aaaaaaaa',
      'aabaaaab',
      'aaaacaaa',
      'aaabaaaa',
      'baaaaaaa',
      'aaaabaaa',
      'aaadaaaa',
      'aaaaaaaa',
    ]],
  },
  {
    id: 'sand-fill',
    palette: {
      a: masterPalette.sandMid,
      b: masterPalette.sandDark,
      c: masterPalette.duneShade,
    },
    frames: [[
      'abababab',
      'baaababa',
      'ababaaab',
      'aababbab',
      'abbcaabb',
      'baabbaba',
      'ababaaba',
      'aabbabba',
    ]],
  },
  {
    id: 'rock-platform',
    palette: {
      a: masterPalette.rockMid,
      b: masterPalette.rockDark,
      c: masterPalette.cloud,
    },
    frames: [[
      'cccccccc',
      'aabaaaba',
      'ababbaba',
      'bbabbabb',
      'ababbaba',
      'babbabbb',
      'ababbaba',
      'bbbbbbbb',
    ]],
  },
  {
    id: 'moss-top',
    palette: {
      a: masterPalette.mossLight,
      b: masterPalette.mossDark,
      c: masterPalette.fernLight,
      d: masterPalette.soilMid,
    },
    frames: [[
      'aacaaaca',
      'abbababa',
      'aaaacaaa',
      'abaaaaab',
      'baaabaaa',
      'aaaaabaa',
      'aaaddaaa',
      'dddddddd',
    ]],
  },
  {
    id: 'soil-fill',
    palette: {
      a: masterPalette.soilMid,
      b: masterPalette.soilDark,
      c: masterPalette.barkDark,
    },
    frames: [[
      'abababab',
      'baaacaba',
      'ababbaab',
      'aabbabab',
      'abccbaba',
      'baaabbab',
      'ababaaba',
      'aabbabba',
    ]],
  },
  {
    id: 'log-platform',
    palette: {
      a: masterPalette.barkLight,
      b: masterPalette.barkDark,
      c: masterPalette.cloud,
    },
    frames: [[
      'cccccccc',
      'aabbaaba',
      'ababbaba',
      'bbabbabb',
      'ababbaba',
      'bbabbabb',
      'ababbaba',
      'bbbbbbbb',
    ]],
  },
  {
    id: 'snow-top',
    palette: {
      a: masterPalette.snowLight,
      b: masterPalette.snowMid,
      c: masterPalette.frostBlue,
      d: masterPalette.permafrost,
    },
    frames: [[
      'aaaaaaaa',
      'aabaaaab',
      'aaaacaaa',
      'aaabaaaa',
      'baaaaaaa',
      'aaaabaaa',
      'aaaddaaa',
      'dddddddd',
    ]],
  },
  {
    id: 'permafrost-fill',
    palette: {
      a: masterPalette.permafrost,
      b: '#4e4958',
      c: masterPalette.iceDark,
    },
    frames: [[
      'abababab',
      'baaababa',
      'ababbbaa',
      'aabbabab',
      'abbcaabb',
      'baabbaba',
      'ababaaba',
      'aabbabba',
    ]],
  },
  {
    id: 'ice-platform',
    palette: {
      a: masterPalette.frostBlue,
      b: masterPalette.iceBlue,
      c: masterPalette.cloud,
    },
    frames: [[
      'cccccccc',
      'aabbaaba',
      'ababbaba',
      'bbabbabb',
      'ababbaba',
      'bbabbabb',
      'ababbaba',
      'bbbbbbbb',
    ]],
  },
];
