import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const treelineFloraSprites: SpriteSource[] = [
  {
    id: 'mountain-hemlock',
    palette: {
      a: masterPalette.hemlockDark,
      b: masterPalette.hemlockLight,
      c: masterPalette.barkLight,
    },
    frames: [[
      '....a...',
      '...aba..',
      '..abbba.',
      '...aba..',
      '..abbba.',
      '.abbbbba',
      '...aca..',
      '..accca.',
      '..accca.',
      '.accccca',
      '...c.c..',
      '........',
    ]],
  },
  {
    id: 'dwarf-birch',
    palette: {
      a: masterPalette.alpineMossDark,
      b: masterPalette.alpineMoss,
      c: masterPalette.birchBark,
    },
    frames: [[
      '..aa....',
      '.abba...',
      '..aa.a..',
      '.abbba..',
      '..abb...',
      '.abbba..',
      '..aa.a..',
      '.abba...',
      '...c....',
      '..ccc...',
      '.ccccc..',
      '........',
    ]],
  },
  {
    id: 'mountain-avens',
    palette: {
      a: masterPalette.cloud,
      b: '#f2d26c',
      c: masterPalette.alpineMoss,
      d: masterPalette.lichenPale,
    },
    frames: [[
      '...a....',
      '..aba...',
      '.aacaa..',
      '..aca...',
      '...c.a..',
      '..ccca..',
      '.ccc....',
      '..cd....',
      '.cddc...',
      '..ddd...',
      '.ddddd..',
      '........',
    ]],
  },
  {
    id: 'reindeer-lichen',
    palette: {
      a: masterPalette.lichenPale,
      b: '#bcc7ae',
      c: masterPalette.alpineStoneLight,
    },
    frames: [[
      '...a....',
      '..aba...',
      '.aabba..',
      '..abba..',
      '.aabba..',
      '..abba..',
      '.ababa..',
      '..aba...',
      '.abcb...',
      '..ccc...',
      '.ccccc..',
      '........',
    ]],
  },
  {
    id: 'moss-campion',
    palette: {
      a: '#d77aa2',
      b: '#f0bdd0',
      c: masterPalette.alpineMoss,
      d: masterPalette.alpineStoneLight,
    },
    frames: [[
      '...a....',
      '..aba...',
      '.abbb...',
      '..aca...',
      '.accca..',
      '..ccc...',
      '.ccdc...',
      '..ddd...',
      '.ddddd..',
      '........',
      '........',
      '........',
    ]],
  },
  {
    id: 'lingonberry',
    palette: {
      a: masterPalette.berryCoral,
      b: masterPalette.berryDark,
      c: masterPalette.alpineMossDark,
      d: masterPalette.alpineMoss,
    },
    frames: [[
      '........',
      '..a.a...',
      '.abbba..',
      '..ccc...',
      '.cdc.c..',
      '..ccc...',
      '.cdddc..',
      '..ddd...',
      '.ddddd..',
      '........',
      '........',
      '........',
    ]],
  },
  {
    id: 'white-arctic-mountain-heather',
    palette: {
      a: masterPalette.cloud,
      b: masterPalette.snowMid,
      c: masterPalette.alpineMossDark,
      d: masterPalette.alpineMoss,
    },
    frames: [[
      '...a....',
      '..aba...',
      '.abbb...',
      '..c.c...',
      '.cdcdc..',
      '..ddd...',
      '.ddddd..',
      '..ddd...',
      '.ddddd..',
      '........',
      '........',
      '........',
    ]],
  },
];
