import type { SpriteSource } from '../engine/sprites';
import { masterPalette } from './palette';

export const worldMapSprites: SpriteSource[] = [
  {
    id: 'map-beach-door',
    palette: {
      a: masterPalette.sandLight,
      b: masterPalette.sandDark,
      c: masterPalette.seaMid,
      d: masterPalette.cloud,
    },
    frames: [[
      '....aa......',
      '...abba.....',
      '..abbbba....',
      '.abbbbbba...',
      '.abdddbba...',
      '.abdddbba...',
      '.abbbbbba...',
      '..abbbba....',
      '..cccccc....',
      '.cccccccc...',
      '............',
      '............',
    ]],
  },
  {
    id: 'map-forest-door',
    palette: {
      a: masterPalette.canopyDark,
      b: masterPalette.canopyLight,
      c: masterPalette.barkDark,
      d: masterPalette.mist,
    },
    frames: [[
      '....aa......',
      '...abba.....',
      '..abbbba....',
      '.abbbbbba...',
      '.acdddcba...',
      '.acdddcba...',
      '.acccccca...',
      '..acccca....',
      '...ccc......',
      '..cc.cc.....',
      '.cc...cc....',
      '............',
    ]],
  },
  {
    id: 'map-coastal-scrub-door',
    palette: {
      a: masterPalette.scrubSageDark,
      b: masterPalette.scrubSageLight,
      c: masterPalette.sandLight,
      d: masterPalette.shorePine,
    },
    frames: [[
      '....aa......',
      '...abba.....',
      '..abbbba....',
      '.abbbbbba...',
      '.abdddbba...',
      '.abdddbba...',
      '.abbbbca....',
      '..abccca....',
      '..cccccc....',
      '.cc....cc...',
      '............',
      '............',
    ]],
  },
  {
    id: 'map-treeline-door',
    palette: {
      a: masterPalette.alpineStoneDark,
      b: masterPalette.alpineStoneMid,
      c: masterPalette.hemlockLight,
      d: masterPalette.snowLight,
    },
    frames: [[
      '....aa......',
      '...abba.....',
      '..abbbba....',
      '.abbbbbba...',
      '.abdddbba...',
      '.abcddcba...',
      '.abcccba....',
      '..abcca.....',
      '..cccccc....',
      '.cc....cc...',
      '............',
      '............',
    ]],
  },
  {
    id: 'map-tundra-door',
    palette: {
      a: masterPalette.snowLight,
      b: masterPalette.snowMid,
      c: masterPalette.iceBlue,
      d: masterPalette.iceDark,
    },
    frames: [[
      '....aa......',
      '...abba.....',
      '..abbbba....',
      '.abbbbbba...',
      '.abcddcba...',
      '.abcddcba...',
      '.abccccc....',
      '..abccc.....',
      '..cccccc....',
      '.cc....cc...',
      '............',
      '............',
    ]],
  },
  {
    id: 'travel-door',
    palette: {
      a: masterPalette.woodLight,
      b: masterPalette.woodDark,
      c: masterPalette.cloud,
      d: masterPalette.ink,
    },
    frames: [[
      '..aaaa..',
      '.abbbba.',
      '.abccba.',
      '.abcdba.',
      '.abcdba.',
      '.abcdba.',
      '.abcdba.',
      '.abcdba.',
      '.abccba.',
      '.abbbba.',
      '..aaaa..',
      '........',
    ]],
  },
  {
    id: 'map-post',
    palette: {
      a: masterPalette.woodLight,
      b: masterPalette.woodDark,
      c: masterPalette.cloud,
      d: masterPalette.tealDark,
    },
    frames: [[
      '...aa...',
      '...aa...',
      '.bbbbbb.',
      '.bccdcb.',
      '.bccdcb.',
      '.bbbbbb.',
      '...aa...',
      '...aa...',
      '...aa...',
      '..abba..',
      '..abba..',
      '........',
    ]],
  },
];
